/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PCR_IBE_ibe0 0x00u         /*!<@brief Input Buffer Enable: Disables */
#define PCR_IBE_ibe1 0x01u         /*!<@brief Input Buffer Enable: Enables */
#define PCR_PFE_pfe1 0x01u         /*!<@brief Passive Filter Enable: Enables */
#define PORT0_PCR0_MUX_mux01 0x01u /*!<@brief Pin Multiplex Control: Alternative 1 (chip-specific) */
#define PORT0_PCR1_MUX_mux01 0x01u /*!<@brief Pin Multiplex Control: Alternative 1 (chip-specific) */
#define PORT2_PCR2_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT2_PCR4_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT2_PCR5_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT2_PCR6_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */

/*! @name PORT1_8 (number 2), LCD_RS232_RX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LCD_RS232_RX_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LCD_RS232_RX_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LCD_RS232_RX_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORT1_9 (number 3), LCD_RS232_TX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LCD_RS232_TX_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LCD_RS232_TX_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LCD_RS232_TX_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORT2_5 (number 19), ADC_IN2
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ADC_IN2_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ADC_IN2_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ADC_IN2_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT2_6 (number 20), ADC_IN4
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ADC_IN4_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ADC_IN4_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ADC_IN4_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT2_13 (number 23), ADC_IN6
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ADC_IN6_PORT PORT2                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ADC_IN6_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ADC_IN6_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT1_11 (number 5), ADC_IN9
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ADC_IN9_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ADC_IN9_PIN 11U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ADC_IN9_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT2_1 (number 15), ADC_IN1
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ADC_IN1_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ADC_IN1_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ADC_IN1_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT2_15 (number 24), SPI_MOSI
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SPI_MOSI_PORT PORT2                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SPI_MOSI_PIN 15U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SPI_MOSI_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORT3_8 (number 42), SPI_MISO
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SPI_MISO_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SPI_MISO_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SPI_MISO_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT2_12 (number 22), SPI_SCK
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SPI_SCK_PORT PORT2                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SPI_SCK_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SPI_SCK_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT1_13 (number 7), I2C_SCL
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_I2C_SCL_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_I2C_SCL_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_I2C_SCL_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT1_12 (number 6), I2C_SDA
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_I2C_SDA_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_I2C_SDA_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_I2C_SDA_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT2_3 (number 17), Modbus_Master_RX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Modbus_Master_RX_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Modbus_Master_RX_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Modbus_Master_RX_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*! @name PORT2_4 (number 18), MASTER_RS485_DE
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MASTER_RS485_DE_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_MASTER_RS485_DE_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_MASTER_RS485_DE_GPIO_PIN 4U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_MASTER_RS485_DE_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_MASTER_RS485_DE_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MASTER_RS485_DE_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MASTER_RS485_DE_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                                /* @} */

/*! @name PORT3_13 (number 37), Modbus_Slave_RX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Modbus_Slave_RX_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Modbus_Slave_RX_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Modbus_Slave_RX_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*! @name PORT3_12 (number 38), Modbus_Slave_TX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Modbus_Slave_TX_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Modbus_Slave_TX_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Modbus_Slave_TX_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*! @name PORT3_28 (number 33), BLE_RX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_BLE_RX_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_BLE_RX_PIN 28U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_BLE_RX_PIN_MASK (1U << 28U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT2_7 (number 21), BLE_TX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_BLE_TX_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_BLE_TX_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_BLE_TX_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORT0_2 (number 51), OUTPUT_KEY_O1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_OUTPUT_KEY_O1_GPIO GPIO0               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_OUTPUT_KEY_O1_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_OUTPUT_KEY_O1_GPIO_PIN 2U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_OUTPUT_KEY_O1_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_OUTPUT_KEY_O1_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_OUTPUT_KEY_O1_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_OUTPUT_KEY_O1_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT0_3 (number 52), OUTPUT_KEY_O2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_OUTPUT_KEY_O2_GPIO GPIO0               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_OUTPUT_KEY_O2_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_OUTPUT_KEY_O2_GPIO_PIN 3U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_OUTPUT_KEY_O2_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_OUTPUT_KEY_O2_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_OUTPUT_KEY_O2_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_OUTPUT_KEY_O2_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT0_6 (number 53), OUTPUT_KEY_O3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_OUTPUT_KEY_O3_GPIO GPIO0               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_OUTPUT_KEY_O3_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_OUTPUT_KEY_O3_GPIO_PIN 6U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_OUTPUT_KEY_O3_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_OUTPUT_KEY_O3_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_OUTPUT_KEY_O3_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_OUTPUT_KEY_O3_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT0_16 (number 54), OUTPUT_KEY_O4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_OUTPUT_KEY_O4_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_OUTPUT_KEY_O4_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_OUTPUT_KEY_O4_GPIO_PIN 16U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_OUTPUT_KEY_O4_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_OUTPUT_KEY_O4_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_OUTPUT_KEY_O4_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_OUTPUT_KEY_O4_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORT0_17 (number 55), OUTPUT_KEY_O5
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_OUTPUT_KEY_O5_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_OUTPUT_KEY_O5_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_OUTPUT_KEY_O5_GPIO_PIN 17U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_OUTPUT_KEY_O5_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_OUTPUT_KEY_O5_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_OUTPUT_KEY_O5_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_OUTPUT_KEY_O5_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORT2_2 (number 16), OUTPUT_DAC_PWR
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_OUTPUT_DAC_PWR_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_OUTPUT_DAC_PWR_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_OUTPUT_DAC_PWR_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORT3_15 (number 35), Modbus_Master_TX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Modbus_Master_TX_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Modbus_Master_TX_PIN 15U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Modbus_Master_TX_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                                  /* @} */

/*! @name PORT3_0 (number 46), PWM_OUT
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_PWM_OUT_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_PWM_OUT_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_PWM_OUT_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT1_0 (number 56), INPUT_IN1        
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_INPUT_IN1_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_INPUT_IN1_GPIO_PIN 0U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_INPUT_IN1_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_INPUT_IN1_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_INPUT_IN1_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_INPUT_IN1_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORT1_1 (number 57), INPUT_IN10       
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_INPUT_IN10_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_INPUT_IN10_GPIO_PIN 1U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_INPUT_IN10_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_INPUT_IN10_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_INPUT_IN10_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_INPUT_IN10_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT1_2 (number 58), INPUT_KEY6       
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_INPUT_KEY6_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_INPUT_KEY6_GPIO_PIN 2U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_INPUT_KEY6_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_INPUT_KEY6_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_INPUT_KEY6_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_INPUT_KEY6_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT1_3 (number 59), INPUT_KEY5       
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_INPUT_KEY5_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_INPUT_KEY5_GPIO_PIN 3U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_INPUT_KEY5_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_INPUT_KEY5_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_INPUT_KEY5_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_INPUT_KEY5_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT1_4 (number 62), INPUT_KEY4       
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_INPUT_KEY4_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_INPUT_KEY4_GPIO_PIN 4U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_INPUT_KEY4_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_INPUT_KEY4_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_INPUT_KEY4_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_INPUT_KEY4_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT1_5 (number 63), INPUT_KEY3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_INPUT_KEY3_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_INPUT_KEY3_GPIO_PIN 5U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_INPUT_KEY3_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_INPUT_KEY3_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_INPUT_KEY3_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_INPUT_KEY3_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT1_6 (number 64), INPUT_KEY2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_INPUT_KEY2_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_INPUT_KEY2_GPIO_PIN 6U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_INPUT_KEY2_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_INPUT_KEY2_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_INPUT_KEY2_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_INPUT_KEY2_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT1_7 (number 1), INPUT_IN5        
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_INPUT_IN5_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_INPUT_IN5_GPIO_PIN 7U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_INPUT_IN5_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_INPUT_IN5_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_INPUT_IN5_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_INPUT_IN5_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
