/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v17.0
processor: MCXA176
package_id: MCXA176VLH
mcu_data: ksdk2_0
processor_version: 26.03.20
external_user_signals: {}
pin_labels:
- {pin_num: '15', pin_signal: P2_1/TRIG_IN7/LPUART0_TXD/LPUART4_RTS_B/CT_INP17/CT2_MAT1/FLEXIO0_D9/SmartDMA_PIO25/ADC1_A0, label: ADC_IN1, identifier: ADC_IN1}
- {pin_num: '19', pin_signal: P2_5/LPUART2_RTS_B/CT_INP15/CT1_MAT1/FLEXIO0_D13/SmartDMA_PIO29/ADC1_A1, label: ADC_IN2, identifier: ADC_IN2}
- {pin_num: '27', pin_signal: USB0_DP/WUU0_IN29, label: ADC_IN3, identifier: ADC_IN3}
- {pin_num: '20', pin_signal: P2_6/TRIG_OUT4/LPSPI1_PCS1/LPUART4_RXD/CT_INP18/CT1_MAT2/FLEXIO0_D14/SmartDMA_PIO30/ADC1_A3, label: ADC_IN4, identifier: ADC_IN4}
- {pin_num: '23', pin_signal: P2_13/TRIG_IN8/LPSPI1_SDO/LPUART1_TXD/CT4_MAT1/CT0_MAT1/FLEXIO0_D21/SmartDMA_PIO17/CAN0_TXD/ADC1_A5/OPAMP0_INN, label: ADC_IN6, identifier: ADC_IN6}
- {pin_num: '5', pin_signal: P1_11/WUU0_IN11/TRIG_OUT2/LPUART1_CTS_B/LPI2C2_SCLS/CT2_MAT1/FLEXIO0_D19/SmartDMA_PIO7/I3C0_PUR/CAN0_RXD/ADC1_A9, label: ADC_IN9, identifier: ADC_IN9}
- {pin_num: '24', pin_signal: P2_15/WUU0_IN21/TRIG_OUT4/LPSPI1_SDI/LPUART1_RTS_B/CT4_MAT3/CT0_MAT2/FLEXIO0_D23/SmartDMA_PIO18/OPAMP0_OUT/ADC0_A2, label: SPI_MOSI,
  identifier: SPI_MOSI}
- {pin_num: '42', pin_signal: P3_8/WUU0_IN23/TRIG_IN3/LPSPI1_SDO/LPUART1_RXD/CT_INP4/PWM0_A1/FLEXIO0_D16/SmartDMA_PIO8/CLKOUT, label: SPI_MISO, identifier: SPI_MISO}
- {pin_num: '22', pin_signal: P2_12/WUU0_IN20/USB0_VBUS_DET/LPSPI1_SCK/LPUART1_RXD/CT4_MAT0/CT0_MAT0/FLEXIO0_D20/SmartDMA_PIO16/CAN0_RXD/ADC0_A5/OPAMP0_INP, label: SPI_SCK,
  identifier: SPI_SCK}
- {pin_num: '39', pin_signal: P3_11/WUU0_IN24/TRIG_IN6/LPSPI1_PCS0/LPUART1_CTS_B/CT1_MAT1/PWM0_B2/FLEXIO0_D19/SmartDMA_PIO11, label: SPI_NSS, identifier: SPI_NSS}
- {pin_num: '7', pin_signal: P1_13/TRIG_IN3/LPI2C1_SCL/LPUART2_TXD/CT2_MAT3/FLEXIO0_D21/SmartDMA_PIO9/ADC1_A11, label: I2C_SCL, identifier: I2C_SCL}
- {pin_num: '6', pin_signal: P1_12/WUU0_IN12/LPI2C1_SDA/LPUART2_RXD/CT2_MAT2/FLEXIO0_D20/SmartDMA_PIO8/ADC1_A10, label: I2C_SDA, identifier: I2C_SDA}
- {pin_num: '16', pin_signal: P2_2/TRIG_IN6/LPUART0_RTS_B/LPUART2_TXD/CT_INP12/CT2_MAT2/FLEXIO0_D10/SmartDMA_PIO26/ADC0_A4/CMP0_IN0/DAC0_OUT, label: OUTPUT_DAC_PWR,
  identifier: Modbus_Master_TX;OUTPUT_DAC_PWR}
- {pin_num: '17', pin_signal: P2_3/WUU0_IN19/TRIG_IN7/LPUART0_CTS_B/LPUART2_RXD/CT_INP13/CT2_MAT3/FLEXIO0_D11/SmartDMA_PIO27/ADC0_A3/CMP1_IN0/ADC1_A4, label: Modbus_Master_RX,
  identifier: Modbus_Master_RX}
- {pin_num: '18', pin_signal: P2_4/LPUART2_CTS_B/CT_INP14/CT1_MAT0/FLEXIO0_D12/SmartDMA_PIO28/ADC0_A1, label: MASTER_RS485_DE, identifier: MASTER_RS485_DE}
- {pin_num: '38', pin_signal: P3_12/LPUART2_RTS_B/LPUART3_TXD/CT1_MAT2/PWM0_X0/FLEXIO0_D20/PWM1_A2/SmartDMA_PIO12, label: Modbus_Slave_TX, identifier: Modbus_Slave_TX}
- {pin_num: '37', pin_signal: P3_13/LPUART2_CTS_B/LPUART3_RXD/CT1_MAT3/PWM0_X1/FLEXIO0_D21/PWM1_B2/SmartDMA_PIO13, label: Modbus_Slave_RX, identifier: Modbus_Slave_RX}
- {pin_num: '36', pin_signal: P3_14/WUU0_IN25/LPUART2_RXD/LPUART3_CTS_B/CT_INP6/PWM0_X2/FLEXIO0_D22/PWM1_A1/SmartDMA_PIO14, label: SLAVE_RS485_DE, identifier: SLAVE_RS485_DE}
- {pin_num: '33', pin_signal: P3_28/WUU0_IN26/TRIG_IN11/LPI2C3_SDA/LPUART4_RXD/CT_INP12/CT3_MAT2/FLEXIO0_D28/PWM1_B3/SmartDMA_PIO28, label: BLE_RX, identifier: BLE_RX}
- {pin_num: '21', pin_signal: P2_7/TRIG_IN5/LPUART4_TXD/CT_INP19/CT1_MAT3/FLEXIO0_D15/SmartDMA_PIO31/VREFI/ADC1_A7/ADC0_A7, label: BLE_TX, identifier: BLE_TX}
- {pin_num: '2', pin_signal: P1_8/WUU0_IN10/FREQME_CLK_IN0/LPUART1_RXD/LPI2C2_SDA/CT_INP8/CT0_MAT2/FLEXIO0_D16/SmartDMA_PIO4/I3C0_SDA, label: LCD_RS232_RX, identifier: LCD_RS232_TX;LCD_RS232_RX}
- {pin_num: '3', pin_signal: P1_9/FREQME_CLK_IN1/LPUART1_TXD/LPI2C2_SCL/CT_INP9/CT0_MAT3/FLEXIO0_D17/SmartDMA_PIO5/I3C0_SCL, label: LCD_RS232_TX, identifier: LCD_RS232_TX}
- {pin_num: '34', pin_signal: P3_27/WUU0_IN30/TRIG_OUT7/LPI2C3_SCL/LPUART4_TXD/CT_INP13/CT3_MAT1/FLEXIO0_D27/PWM1_A3/SmartDMA_PIO27, label: BLE_EN, identifier: BLE_EN}
- {pin_num: '51', pin_signal: P0_2/TDO/SWO/LPUART0_RXD/LPSPI0_SCK/CT0_MAT0/UTICK_CAP0/FLEXIO0_D2/I3C0_PUR, label: OUTPUT_KEY_O1, identifier: OUTPUT_KEY_O1}
- {pin_num: '52', pin_signal: P0_3/TDI/LPUART0_TXD/LPSPI0_SDO/CT0_MAT1/UTICK_CAP1/FLEXIO0_D3/CMP0_OUT/CMP1_IN1/ADC0_A14, label: OUTPUT_KEY_O2, identifier: OUTPUT_KEY_O2}
- {pin_num: '53', pin_signal: P0_6/ISPMODE_N/LPI2C0_HREQ/LPSPI0_PCS1/CT_INP2/FLEXIO0_D6/SmartDMA_PIO2/CMP1_OUT/CLKOUT/ADC0_A15, label: OUTPUT_KEY_O3, identifier: OUTPUT_KEY_O3}
- {pin_num: '54', pin_signal: P0_16/WUU0_IN2/LPI2C0_SDA/LPSPI0_PCS2/CT0_MAT0/UTICK_CAP2/FLEXIO0_D0/SmartDMA_PIO6/I3C0_SDA, label: OUTPUT_KEY_O4, identifier: OUTPUT_KEY_O4}
- {pin_num: '55', pin_signal: P0_17/LPI2C0_SCL/LPSPI0_PCS3/CT0_MAT1/UTICK_CAP3/FLEXIO0_D1/SmartDMA_PIO7/I3C0_SCL, label: OUTPUT_KEY_O5, identifier: OUTPUT_KEY_O5}
- {pin_num: '35', pin_signal: P3_15/LPUART2_TXD/LPUART3_RTS_B/CT_INP7/PWM0_X3/FLEXIO0_D23/PWM1_B1/SmartDMA_PIO15, label: Modbus_Master_TX, identifier: Modbus_Master_TX}
- {pin_num: '64', pin_signal: P1_6/TRIG_IN2/LPSPI0_PCS1/LPUART2_RTS_B/CT_INP6/CT4_MAT0/FLEXIO0_D14/SmartDMA_PIO2/ADC0_A22, label: INPUT_KEY2, identifier: PWM_OUT;INPUT_KEY2}
- {pin_num: '46', pin_signal: P3_0/WUU0_IN22/TRIG_IN0/LPUART3_RXD/CT_INP16/PWM0_A0/FLEXIO0_D8/PWM1_X0/SmartDMA_PIO0, label: PWM_OUT, identifier: PWM_OUT}
- {pin_num: '56', pin_signal: P1_0/WUU0_IN6/LPTMR0_ALT3/TRIG_IN0/LPSPI0_SDO/LPI2C1_SDA/CT_INP4/CT0_MAT2/FLEXIO0_D8/ADC0_A16/CMP0_IN3, label: 'INPUT_IN1        ',
  identifier: INPUT_IN1}
- {pin_num: '57', pin_signal: P1_1/TRIG_IN1/LPSPI0_SCK/LPI2C1_SCL/CT_INP5/CT0_MAT3/FLEXIO0_D9/ADC0_A17/CMP1_IN3, label: 'INPUT_IN10       ', identifier: INPUT_IN10}
- {pin_num: '58', pin_signal: P1_2/TRIG_OUT0/LPSPI0_SDI/LPI2C1_SDAS/CT1_MAT0/CT_INP0/FLEXIO0_D10/CAN0_TXD/ADC0_A18, label: 'INPUT_KEY6       ', identifier: INPUT_KEY6}
- {pin_num: '59', pin_signal: P1_3/WUU0_IN7/TRIG_OUT1/LPSPI0_PCS0/LPI2C1_SCLS/CT1_MAT1/CT_INP1/FLEXIO0_D11/CAN0_RXD/ADC0_A19/CMP0_IN1, label: 'INPUT_KEY5       ',
  identifier: INPUT_KEY5}
- {pin_num: '62', pin_signal: P1_4/WUU0_IN8/FREQME_CLK_IN0/LPSPI0_PCS3/LPUART2_RXD/CT1_MAT2/FLEXIO0_D12/SmartDMA_PIO0/ADC0_A20/CMP0_IN2, label: 'INPUT_KEY4       ',
  identifier: INPUT_KEY4}
- {pin_num: '63', pin_signal: P1_5/FREQME_CLK_IN1/LPSPI0_PCS2/LPUART2_TXD/CT1_MAT3/FLEXIO0_D13/SmartDMA_PIO1/ADC0_A21/CMP1_IN2, label: INPUT_KEY3, identifier: INPUT_KEY3}
- {pin_num: '1', pin_signal: P1_7/WUU0_IN9/TRIG_OUT2/LPUART2_CTS_B/CT_INP7/CT4_MAT1/FLEXIO0_D15/SmartDMA_PIO3/ADC0_A23, label: 'INPUT_IN5        ', identifier: INPUT_IN5}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '50', peripheral: SWD, signal: SWCLK, pin_signal: P0_1/TCLK/SWCLK/LPUART0_CTS_B/LPSPI0_SDI/CT_INP1/FLEXIO0_D1}
  - {pin_num: '49', peripheral: SWD, signal: SWDIO, pin_signal: P0_0/TMS/SWDIO/LPUART0_RTS_B/LPSPI0_PCS0/CT_INP0/FLEXIO0_D0}
  - {pin_num: '2', peripheral: LPUART1, signal: RX, pin_signal: P1_8/WUU0_IN10/FREQME_CLK_IN0/LPUART1_RXD/LPI2C2_SDA/CT_INP8/CT0_MAT2/FLEXIO0_D16/SmartDMA_PIO4/I3C0_SDA,
    identifier: LCD_RS232_RX}
  - {pin_num: '3', peripheral: LPUART1, signal: TX, pin_signal: P1_9/FREQME_CLK_IN1/LPUART1_TXD/LPI2C2_SCL/CT_INP9/CT0_MAT3/FLEXIO0_D17/SmartDMA_PIO5/I3C0_SCL}
  - {pin_num: '19', peripheral: ADC1, signal: 'A, 1', pin_signal: P2_5/LPUART2_RTS_B/CT_INP15/CT1_MAT1/FLEXIO0_D13/SmartDMA_PIO29/ADC1_A1}
  - {pin_num: '20', peripheral: ADC1, signal: 'A, 3', pin_signal: P2_6/TRIG_OUT4/LPSPI1_PCS1/LPUART4_RXD/CT_INP18/CT1_MAT2/FLEXIO0_D14/SmartDMA_PIO30/ADC1_A3}
  - {pin_num: '23', peripheral: ADC1, signal: 'A, 5', pin_signal: P2_13/TRIG_IN8/LPSPI1_SDO/LPUART1_TXD/CT4_MAT1/CT0_MAT1/FLEXIO0_D21/SmartDMA_PIO17/CAN0_TXD/ADC1_A5/OPAMP0_INN}
  - {pin_num: '5', peripheral: ADC1, signal: 'A, 9', pin_signal: P1_11/WUU0_IN11/TRIG_OUT2/LPUART1_CTS_B/LPI2C2_SCLS/CT2_MAT1/FLEXIO0_D19/SmartDMA_PIO7/I3C0_PUR/CAN0_RXD/ADC1_A9}
  - {pin_num: '15', peripheral: ADC1, signal: 'A, 0', pin_signal: P2_1/TRIG_IN7/LPUART0_TXD/LPUART4_RTS_B/CT_INP17/CT2_MAT1/FLEXIO0_D9/SmartDMA_PIO25/ADC1_A0}
  - {pin_num: '24', peripheral: LPSPI1, signal: IN, pin_signal: P2_15/WUU0_IN21/TRIG_OUT4/LPSPI1_SDI/LPUART1_RTS_B/CT4_MAT3/CT0_MAT2/FLEXIO0_D23/SmartDMA_PIO18/OPAMP0_OUT/ADC0_A2}
  - {pin_num: '42', peripheral: LPSPI1, signal: OUT, pin_signal: P3_8/WUU0_IN23/TRIG_IN3/LPSPI1_SDO/LPUART1_RXD/CT_INP4/PWM0_A1/FLEXIO0_D16/SmartDMA_PIO8/CLKOUT}
  - {pin_num: '22', peripheral: LPSPI1, signal: SCK, pin_signal: P2_12/WUU0_IN20/USB0_VBUS_DET/LPSPI1_SCK/LPUART1_RXD/CT4_MAT0/CT0_MAT0/FLEXIO0_D20/SmartDMA_PIO16/CAN0_RXD/ADC0_A5/OPAMP0_INP}
  - {pin_num: '7', peripheral: LPI2C1, signal: SCL, pin_signal: P1_13/TRIG_IN3/LPI2C1_SCL/LPUART2_TXD/CT2_MAT3/FLEXIO0_D21/SmartDMA_PIO9/ADC1_A11}
  - {pin_num: '6', peripheral: LPI2C1, signal: SDA, pin_signal: P1_12/WUU0_IN12/LPI2C1_SDA/LPUART2_RXD/CT2_MAT2/FLEXIO0_D20/SmartDMA_PIO8/ADC1_A10}
  - {pin_num: '17', peripheral: LPUART2, signal: RX, pin_signal: P2_3/WUU0_IN19/TRIG_IN7/LPUART0_CTS_B/LPUART2_RXD/CT_INP13/CT2_MAT3/FLEXIO0_D11/SmartDMA_PIO27/ADC0_A3/CMP1_IN0/ADC1_A4}
  - {pin_num: '18', peripheral: GPIO2, signal: 'GPIO, 4', pin_signal: P2_4/LPUART2_CTS_B/CT_INP14/CT1_MAT0/FLEXIO0_D12/SmartDMA_PIO28/ADC0_A1, direction: OUTPUT,
    gpio_init_state: 'false'}
  - {pin_num: '37', peripheral: LPUART3, signal: RX, pin_signal: P3_13/LPUART2_CTS_B/LPUART3_RXD/CT1_MAT3/PWM0_X1/FLEXIO0_D21/PWM1_B2/SmartDMA_PIO13}
  - {pin_num: '38', peripheral: LPUART3, signal: TX, pin_signal: P3_12/LPUART2_RTS_B/LPUART3_TXD/CT1_MAT2/PWM0_X0/FLEXIO0_D20/PWM1_A2/SmartDMA_PIO12}
  - {pin_num: '33', peripheral: LPUART4, signal: RX, pin_signal: P3_28/WUU0_IN26/TRIG_IN11/LPI2C3_SDA/LPUART4_RXD/CT_INP12/CT3_MAT2/FLEXIO0_D28/PWM1_B3/SmartDMA_PIO28}
  - {pin_num: '21', peripheral: LPUART4, signal: TX, pin_signal: P2_7/TRIG_IN5/LPUART4_TXD/CT_INP19/CT1_MAT3/FLEXIO0_D15/SmartDMA_PIO31/VREFI/ADC1_A7/ADC0_A7}
  - {pin_num: '51', peripheral: GPIO0, signal: 'GPIO, 2', pin_signal: P0_2/TDO/SWO/LPUART0_RXD/LPSPI0_SCK/CT0_MAT0/UTICK_CAP0/FLEXIO0_D2/I3C0_PUR, direction: OUTPUT}
  - {pin_num: '52', peripheral: GPIO0, signal: 'GPIO, 3', pin_signal: P0_3/TDI/LPUART0_TXD/LPSPI0_SDO/CT0_MAT1/UTICK_CAP1/FLEXIO0_D3/CMP0_OUT/CMP1_IN1/ADC0_A14, direction: OUTPUT}
  - {pin_num: '53', peripheral: GPIO0, signal: 'GPIO, 6', pin_signal: P0_6/ISPMODE_N/LPI2C0_HREQ/LPSPI0_PCS1/CT_INP2/FLEXIO0_D6/SmartDMA_PIO2/CMP1_OUT/CLKOUT/ADC0_A15,
    direction: OUTPUT}
  - {pin_num: '54', peripheral: GPIO0, signal: 'GPIO, 16', pin_signal: P0_16/WUU0_IN2/LPI2C0_SDA/LPSPI0_PCS2/CT0_MAT0/UTICK_CAP2/FLEXIO0_D0/SmartDMA_PIO6/I3C0_SDA,
    direction: OUTPUT}
  - {pin_num: '55', peripheral: GPIO0, signal: 'GPIO, 17', pin_signal: P0_17/LPI2C0_SCL/LPSPI0_PCS3/CT0_MAT1/UTICK_CAP3/FLEXIO0_D1/SmartDMA_PIO7/I3C0_SCL, direction: OUTPUT}
  - {pin_num: '16', peripheral: DAC0, signal: OUT, pin_signal: P2_2/TRIG_IN6/LPUART0_RTS_B/LPUART2_TXD/CT_INP12/CT2_MAT2/FLEXIO0_D10/SmartDMA_PIO26/ADC0_A4/CMP0_IN0/DAC0_OUT,
    identifier: OUTPUT_DAC_PWR}
  - {pin_num: '35', peripheral: LPUART2, signal: TX, pin_signal: P3_15/LPUART2_TXD/LPUART3_RTS_B/CT_INP7/PWM0_X3/FLEXIO0_D23/PWM1_B1/SmartDMA_PIO15}
  - {pin_num: '46', peripheral: FLEXPWM0, signal: 'A, 0', pin_signal: P3_0/WUU0_IN22/TRIG_IN0/LPUART3_RXD/CT_INP16/PWM0_A0/FLEXIO0_D8/PWM1_X0/SmartDMA_PIO0, direction: OUTPUT}
  - {pin_num: '4', peripheral: ADC1, signal: 'A, 8', pin_signal: P1_10/LPUART1_RTS_B/LPI2C2_SDAS/CT2_MAT0/FLEXIO0_D18/SmartDMA_PIO6/CAN0_TXD/ADC1_A8}
  - {pin_num: '56', peripheral: GPIO1, signal: 'GPIO, 0', pin_signal: P1_0/WUU0_IN6/LPTMR0_ALT3/TRIG_IN0/LPSPI0_SDO/LPI2C1_SDA/CT_INP4/CT0_MAT2/FLEXIO0_D8/ADC0_A16/CMP0_IN3,
    direction: INPUT, passive_filter: enable}
  - {pin_num: '57', peripheral: GPIO1, signal: 'GPIO, 1', pin_signal: P1_1/TRIG_IN1/LPSPI0_SCK/LPI2C1_SCL/CT_INP5/CT0_MAT3/FLEXIO0_D9/ADC0_A17/CMP1_IN3, direction: INPUT,
    passive_filter: enable}
  - {pin_num: '58', peripheral: GPIO1, signal: 'GPIO, 2', pin_signal: P1_2/TRIG_OUT0/LPSPI0_SDI/LPI2C1_SDAS/CT1_MAT0/CT_INP0/FLEXIO0_D10/CAN0_TXD/ADC0_A18, direction: INPUT}
  - {pin_num: '59', peripheral: GPIO1, signal: 'GPIO, 3', pin_signal: P1_3/WUU0_IN7/TRIG_OUT1/LPSPI0_PCS0/LPI2C1_SCLS/CT1_MAT1/CT_INP1/FLEXIO0_D11/CAN0_RXD/ADC0_A19/CMP0_IN1,
    direction: INPUT}
  - {pin_num: '62', peripheral: GPIO1, signal: 'GPIO, 4', pin_signal: P1_4/WUU0_IN8/FREQME_CLK_IN0/LPSPI0_PCS3/LPUART2_RXD/CT1_MAT2/FLEXIO0_D12/SmartDMA_PIO0/ADC0_A20/CMP0_IN2,
    direction: INPUT}
  - {pin_num: '63', peripheral: GPIO1, signal: 'GPIO, 5', pin_signal: P1_5/FREQME_CLK_IN1/LPSPI0_PCS2/LPUART2_TXD/CT1_MAT3/FLEXIO0_D13/SmartDMA_PIO1/ADC0_A21/CMP1_IN2,
    direction: INPUT}
  - {pin_num: '64', peripheral: GPIO1, signal: 'GPIO, 6', pin_signal: P1_6/TRIG_IN2/LPSPI0_PCS1/LPUART2_RTS_B/CT_INP6/CT4_MAT0/FLEXIO0_D14/SmartDMA_PIO2/ADC0_A22,
    identifier: INPUT_KEY2, direction: INPUT}
  - {pin_num: '1', peripheral: GPIO1, signal: 'GPIO, 7', pin_signal: P1_7/WUU0_IN9/TRIG_OUT2/LPUART2_CTS_B/CT_INP7/CT4_MAT1/FLEXIO0_D15/SmartDMA_PIO3/ADC0_A23, direction: INPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* PORT0: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT0);
    /* PORT1: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT1);
    /* PORT2: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT2);
    /* PORT3: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT3);
    /* GPIO0: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateGPIO0);
    /* GPIO1: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateGPIO1);
    /* GPIO2: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateGPIO2);
    /* PORT0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT0_RST_SHIFT_RSTn);
    /* GPIO0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kGPIO0_RST_SHIFT_RSTn);
    /* GPIO1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kGPIO1_RST_SHIFT_RSTn);
    /* PORT1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT1_RST_SHIFT_RSTn);
    /* ADC1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kADC1_RST_SHIFT_RSTn);
    /* LPI2C1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kLPI2C1_RST_SHIFT_RSTn);
    /* LPUART1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kLPUART1_RST_SHIFT_RSTn);
    /* PORT2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT2_RST_SHIFT_RSTn);
    /* LPSPI1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kLPSPI1_RST_SHIFT_RSTn);
    /* DAC0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kDAC0_RST_SHIFT_RSTn);
    /* LPUART2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kLPUART2_RST_SHIFT_RSTn);
    /* GPIO2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kGPIO2_RST_SHIFT_RSTn);
    /* LPUART4 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kLPUART4_RST_SHIFT_RSTn);
    /* FLEXPWM0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kFLEXPWM0_RST_SHIFT_RSTn);
    /* PORT3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT3_RST_SHIFT_RSTn);
    /* LPUART3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kLPUART3_RST_SHIFT_RSTn);

    PORT0->PCR[0] = ((PORT0->PCR[0] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                     /* Pin Multiplex Control: PORT0_0 (pin 49) is configured as SWDIO. */
                     | PORT_PCR_MUX(PORT0_PCR0_MUX_mux01)

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT0->PCR[1] = ((PORT0->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                     /* Pin Multiplex Control: PORT0_1 (pin 50) is configured as SWCLK. */
                     | PORT_PCR_MUX(PORT0_PCR1_MUX_mux01)

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT0_16 (pin 54) is configured as P0_16 */
    PORT_SetPinMux(BOARD_INITPINS_OUTPUT_KEY_O4_PORT, BOARD_INITPINS_OUTPUT_KEY_O4_PIN, kPORT_MuxAlt0);

    PORT0->PCR[16] = ((PORT0->PCR[16] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT0_17 (pin 55) is configured as P0_17 */
    PORT_SetPinMux(BOARD_INITPINS_OUTPUT_KEY_O5_PORT, BOARD_INITPINS_OUTPUT_KEY_O5_PIN, kPORT_MuxAlt0);

    PORT0->PCR[17] = ((PORT0->PCR[17] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT0_2 (pin 51) is configured as P0_2 */
    PORT_SetPinMux(BOARD_INITPINS_OUTPUT_KEY_O1_PORT, BOARD_INITPINS_OUTPUT_KEY_O1_PIN, kPORT_MuxAlt0);

    PORT0->PCR[2] = ((PORT0->PCR[2] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT0_3 (pin 52) is configured as P0_3 */
    PORT_SetPinMux(BOARD_INITPINS_OUTPUT_KEY_O2_PORT, BOARD_INITPINS_OUTPUT_KEY_O2_PIN, kPORT_MuxAlt0);

    PORT0->PCR[3] = ((PORT0->PCR[3] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT0_6 (pin 53) is configured as P0_6 */
    PORT_SetPinMux(BOARD_INITPINS_OUTPUT_KEY_O3_PORT, BOARD_INITPINS_OUTPUT_KEY_O3_PIN, kPORT_MuxAlt0);

    PORT0->PCR[6] = ((PORT0->PCR[6] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_0 (pin 56) is configured as P1_0 */
    PORT_SetPinMux(BOARD_INITPINS_INPUT_IN1_PORT, BOARD_INITPINS_INPUT_IN1_PIN, kPORT_MuxAlt0);

    PORT1->PCR[0] = ((PORT1->PCR[0] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PFE_MASK | PORT_PCR_IBE_MASK)))

                     /* Passive Filter Enable: Enables. */
                     | PORT_PCR_PFE(PCR_PFE_pfe1)

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_1 (pin 57) is configured as P1_1 */
    PORT_SetPinMux(BOARD_INITPINS_INPUT_IN10_PORT, BOARD_INITPINS_INPUT_IN10_PIN, kPORT_MuxAlt0);

    PORT1->PCR[1] = ((PORT1->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PFE_MASK | PORT_PCR_IBE_MASK)))

                     /* Passive Filter Enable: Enables. */
                     | PORT_PCR_PFE(PCR_PFE_pfe1)

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_10 (pin 4) is configured as ADC1_A8 */
    PORT_SetPinMux(PORT1, 10U, kPORT_MuxAlt0);

    PORT1->PCR[10] = ((PORT1->PCR[10] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Disables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT1_11 (pin 5) is configured as ADC1_A9 */
    PORT_SetPinMux(BOARD_INITPINS_ADC_IN9_PORT, BOARD_INITPINS_ADC_IN9_PIN, kPORT_MuxAlt0);

    PORT1->PCR[11] = ((PORT1->PCR[11] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Disables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT1_12 (pin 6) is configured as LPI2C1_SDA */
    PORT_SetPinMux(BOARD_INITPINS_I2C_SDA_PORT, BOARD_INITPINS_I2C_SDA_PIN, kPORT_MuxAlt2);

    PORT1->PCR[12] = ((PORT1->PCR[12] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_13 (pin 7) is configured as LPI2C1_SCL */
    PORT_SetPinMux(BOARD_INITPINS_I2C_SCL_PORT, BOARD_INITPINS_I2C_SCL_PIN, kPORT_MuxAlt2);

    PORT1->PCR[13] = ((PORT1->PCR[13] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_2 (pin 58) is configured as P1_2 */
    PORT_SetPinMux(BOARD_INITPINS_INPUT_KEY6_PORT, BOARD_INITPINS_INPUT_KEY6_PIN, kPORT_MuxAlt0);

    PORT1->PCR[2] = ((PORT1->PCR[2] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_3 (pin 59) is configured as P1_3 */
    PORT_SetPinMux(BOARD_INITPINS_INPUT_KEY5_PORT, BOARD_INITPINS_INPUT_KEY5_PIN, kPORT_MuxAlt0);

    PORT1->PCR[3] = ((PORT1->PCR[3] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_4 (pin 62) is configured as P1_4 */
    PORT_SetPinMux(BOARD_INITPINS_INPUT_KEY4_PORT, BOARD_INITPINS_INPUT_KEY4_PIN, kPORT_MuxAlt0);

    PORT1->PCR[4] = ((PORT1->PCR[4] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_5 (pin 63) is configured as P1_5 */
    PORT_SetPinMux(BOARD_INITPINS_INPUT_KEY3_PORT, BOARD_INITPINS_INPUT_KEY3_PIN, kPORT_MuxAlt0);

    PORT1->PCR[5] = ((PORT1->PCR[5] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_6 (pin 64) is configured as P1_6 */
    PORT_SetPinMux(BOARD_INITPINS_INPUT_KEY2_PORT, BOARD_INITPINS_INPUT_KEY2_PIN, kPORT_MuxAlt0);

    PORT1->PCR[6] = ((PORT1->PCR[6] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_7 (pin 1) is configured as P1_7 */
    PORT_SetPinMux(BOARD_INITPINS_INPUT_IN5_PORT, BOARD_INITPINS_INPUT_IN5_PIN, kPORT_MuxAlt0);

    PORT1->PCR[7] = ((PORT1->PCR[7] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_8 (pin 2) is configured as LPUART1_RXD */
    PORT_SetPinMux(BOARD_INITPINS_LCD_RS232_RX_PORT, BOARD_INITPINS_LCD_RS232_RX_PIN, kPORT_MuxAlt2);

    PORT1->PCR[8] = ((PORT1->PCR[8] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_9 (pin 3) is configured as LPUART1_TXD */
    PORT_SetPinMux(BOARD_INITPINS_LCD_RS232_TX_PORT, BOARD_INITPINS_LCD_RS232_TX_PIN, kPORT_MuxAlt2);

    PORT1->PCR[9] = ((PORT1->PCR[9] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT2_1 (pin 15) is configured as ADC1_A0 */
    PORT_SetPinMux(BOARD_INITPINS_ADC_IN1_PORT, BOARD_INITPINS_ADC_IN1_PIN, kPORT_MuxAlt0);

    PORT2->PCR[1] = ((PORT2->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Disables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT2_12 (pin 22) is configured as LPSPI1_SCK */
    PORT_SetPinMux(BOARD_INITPINS_SPI_SCK_PORT, BOARD_INITPINS_SPI_SCK_PIN, kPORT_MuxAlt2);

    PORT2->PCR[12] = ((PORT2->PCR[12] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT2_13 (pin 23) is configured as ADC1_A5 */
    PORT_SetPinMux(BOARD_INITPINS_ADC_IN6_PORT, BOARD_INITPINS_ADC_IN6_PIN, kPORT_MuxAlt0);

    PORT2->PCR[13] = ((PORT2->PCR[13] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Disables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT2_15 (pin 24) is configured as LPSPI1_SDI */
    PORT_SetPinMux(BOARD_INITPINS_SPI_MOSI_PORT, BOARD_INITPINS_SPI_MOSI_PIN, kPORT_MuxAlt2);

    PORT2->PCR[15] = ((PORT2->PCR[15] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT2->PCR[2] = ((PORT2->PCR[2] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                     /* Pin Multiplex Control: PORT2_2 (pin 16) is configured as DAC0_OUT. */
                     | PORT_PCR_MUX(PORT2_PCR2_MUX_mux00)

                     /* Input Buffer Enable: Disables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT2_3 (pin 17) is configured as LPUART2_RXD */
    PORT_SetPinMux(BOARD_INITPINS_Modbus_Master_RX_PORT, BOARD_INITPINS_Modbus_Master_RX_PIN, kPORT_MuxAlt3);

    PORT2->PCR[3] = ((PORT2->PCR[3] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT2->PCR[4] = ((PORT2->PCR[4] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                     /* Pin Multiplex Control: PORT2_4 (pin 18) is configured as P2_4. */
                     | PORT_PCR_MUX(PORT2_PCR4_MUX_mux00)

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT2->PCR[5] = ((PORT2->PCR[5] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                     /* Pin Multiplex Control: PORT2_5 (pin 19) is configured as ADC1_A1. */
                     | PORT_PCR_MUX(PORT2_PCR5_MUX_mux00)

                     /* Input Buffer Enable: Disables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe0));

    PORT2->PCR[6] = ((PORT2->PCR[6] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                     /* Pin Multiplex Control: PORT2_6 (pin 20) is configured as ADC1_A3. */
                     | PORT_PCR_MUX(PORT2_PCR6_MUX_mux00)

                     /* Input Buffer Enable: Disables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT2_7 (pin 21) is configured as LPUART4_TXD */
    PORT_SetPinMux(BOARD_INITPINS_BLE_TX_PORT, BOARD_INITPINS_BLE_TX_PIN, kPORT_MuxAlt3);

    PORT2->PCR[7] = ((PORT2->PCR[7] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_0 (pin 46) is configured as PWM0_A0 */
    PORT_SetPinMux(BOARD_INITPINS_PWM_OUT_PORT, BOARD_INITPINS_PWM_OUT_PIN, kPORT_MuxAlt5);

    PORT3->PCR[0] = ((PORT3->PCR[0] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_12 (pin 38) is configured as LPUART3_TXD */
    PORT_SetPinMux(BOARD_INITPINS_Modbus_Slave_TX_PORT, BOARD_INITPINS_Modbus_Slave_TX_PIN, kPORT_MuxAlt3);

    PORT3->PCR[12] = ((PORT3->PCR[12] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_13 (pin 37) is configured as LPUART3_RXD */
    PORT_SetPinMux(BOARD_INITPINS_Modbus_Slave_RX_PORT, BOARD_INITPINS_Modbus_Slave_RX_PIN, kPORT_MuxAlt3);

    PORT3->PCR[13] = ((PORT3->PCR[13] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_15 (pin 35) is configured as LPUART2_TXD */
    PORT_SetPinMux(BOARD_INITPINS_Modbus_Master_TX_PORT, BOARD_INITPINS_Modbus_Master_TX_PIN, kPORT_MuxAlt2);

    PORT3->PCR[15] = ((PORT3->PCR[15] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_28 (pin 33) is configured as LPUART4_RXD */
    PORT_SetPinMux(BOARD_INITPINS_BLE_RX_PORT, BOARD_INITPINS_BLE_RX_PIN, kPORT_MuxAlt3);

    PORT3->PCR[28] = ((PORT3->PCR[28] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_8 (pin 42) is configured as LPSPI1_SDO */
    PORT_SetPinMux(BOARD_INITPINS_SPI_MISO_PORT, BOARD_INITPINS_SPI_MISO_PIN, kPORT_MuxAlt2);

    PORT3->PCR[8] = ((PORT3->PCR[8] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    gpio_pin_config_t OUTPUT_KEY_O1_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO0_2 (pin 51)  */
    GPIO_PinInit(BOARD_INITPINS_OUTPUT_KEY_O1_GPIO, BOARD_INITPINS_OUTPUT_KEY_O1_PIN, &OUTPUT_KEY_O1_config);

    gpio_pin_config_t OUTPUT_KEY_O2_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO0_3 (pin 52)  */
    GPIO_PinInit(BOARD_INITPINS_OUTPUT_KEY_O2_GPIO, BOARD_INITPINS_OUTPUT_KEY_O2_PIN, &OUTPUT_KEY_O2_config);

    gpio_pin_config_t OUTPUT_KEY_O3_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO0_6 (pin 53)  */
    GPIO_PinInit(BOARD_INITPINS_OUTPUT_KEY_O3_GPIO, BOARD_INITPINS_OUTPUT_KEY_O3_PIN, &OUTPUT_KEY_O3_config);

    gpio_pin_config_t OUTPUT_KEY_O4_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO0_16 (pin 54)  */
    GPIO_PinInit(BOARD_INITPINS_OUTPUT_KEY_O4_GPIO, BOARD_INITPINS_OUTPUT_KEY_O4_PIN, &OUTPUT_KEY_O4_config);

    gpio_pin_config_t OUTPUT_KEY_O5_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO0_17 (pin 55)  */
    GPIO_PinInit(BOARD_INITPINS_OUTPUT_KEY_O5_GPIO, BOARD_INITPINS_OUTPUT_KEY_O5_PIN, &OUTPUT_KEY_O5_config);

    gpio_pin_config_t INPUT_IN1_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO1_0 (pin 56)  */
    GPIO_PinInit(BOARD_INITPINS_INPUT_IN1_GPIO, BOARD_INITPINS_INPUT_IN1_PIN, &INPUT_IN1_config);

    gpio_pin_config_t INPUT_IN10_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO1_1 (pin 57)  */
    GPIO_PinInit(BOARD_INITPINS_INPUT_IN10_GPIO, BOARD_INITPINS_INPUT_IN10_PIN, &INPUT_IN10_config);

    gpio_pin_config_t INPUT_KEY6_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO1_2 (pin 58)  */
    GPIO_PinInit(BOARD_INITPINS_INPUT_KEY6_GPIO, BOARD_INITPINS_INPUT_KEY6_PIN, &INPUT_KEY6_config);

    gpio_pin_config_t INPUT_KEY5_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO1_3 (pin 59)  */
    GPIO_PinInit(BOARD_INITPINS_INPUT_KEY5_GPIO, BOARD_INITPINS_INPUT_KEY5_PIN, &INPUT_KEY5_config);

    gpio_pin_config_t INPUT_KEY4_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO1_4 (pin 62)  */
    GPIO_PinInit(BOARD_INITPINS_INPUT_KEY4_GPIO, BOARD_INITPINS_INPUT_KEY4_PIN, &INPUT_KEY4_config);

    gpio_pin_config_t INPUT_KEY3_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO1_5 (pin 63)  */
    GPIO_PinInit(BOARD_INITPINS_INPUT_KEY3_GPIO, BOARD_INITPINS_INPUT_KEY3_PIN, &INPUT_KEY3_config);

    gpio_pin_config_t INPUT_KEY2_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO1_6 (pin 64)  */
    GPIO_PinInit(BOARD_INITPINS_INPUT_KEY2_GPIO, BOARD_INITPINS_INPUT_KEY2_PIN, &INPUT_KEY2_config);

    gpio_pin_config_t INPUT_IN5_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO1_7 (pin 1)  */
    GPIO_PinInit(BOARD_INITPINS_INPUT_IN5_GPIO, BOARD_INITPINS_INPUT_IN5_PIN, &INPUT_IN5_config);

    gpio_pin_config_t MASTER_RS485_DE_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO2_4 (pin 18)  */
    GPIO_PinInit(BOARD_INITPINS_MASTER_RS485_DE_GPIO, BOARD_INITPINS_MASTER_RS485_DE_PIN, &MASTER_RS485_DE_config);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
