/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v15.0
processor: MCXA176
package_id: MCXA176VLH
mcu_data: ksdk2_0
processor_version: 26.03.20
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 89ff4954-f7e4-4892-ba91-8305e887d59f
  called_from_default_init: true
  selectedCore: cm33_core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
  - global_init: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'uart_cmsis_common'
- type_id: 'uart_cmsis_common'
- global_USART_CMSIS_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'gpio_adapter_common'
- type_id: 'gpio_adapter_common'
- global_gpio_adapter_common:
  - commonSetting:
    - HAL_GPIO_CONFLICT_CHECK_ENABLE: 'true'
    - HAL_GPIO_ISR_PRIORITY: '3'
    - HAL_GpioPreInit: 'true'
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * DMA0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'DMA0'
- type: 'edma4'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'edma4_2.9.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'DMA0'
- config_sets:
  - fsl_edma:
    - dmamux_devices: []
    - common_settings:
      - vars: []
      - enableHaltOnError: 'true'
      - enableDebugMode: 'false'
      - enableRoundRobinArbitration: 'fixedPriority'
      - enableGlobalChannelLink: 'true'
      - enableMasterIdReplication: 'false'
    - dma_table:
      - 0: []
      - 1: []
      - 2: []
      - 3: []
      - 4: []
      - 5: []
    - edma_channels:
      - 0:
        - apiMode: 'trans'
        - edma_channel:
          - channel_prefix_id: 'CH2'
          - uid: '1787886288155'
          - eDMAn: '2'
          - eDMA_source: 'kDma0RequestMuxAdc1FifoRequest'
          - init_channel_priority: 'false'
          - edma_channel_Preemption:
            - enableChannelPreemption: 'false'
            - enablePreemptAbility: 'false'
            - channelPriority: '0'
          - masterIdReplicationEnable: 'noInit'
          - protectionLevel: 'noInit'
          - enable_custom_name: 'true'
          - handle_custom_name: 'g_adc1DmaHandle'
        - resetChannel: 'true'
        - enableChannelRequest: 'true'
        - enableAutoStop: 'false'
        - tcd_pool_enable: 'false'
        - tcd_settings:
          - tcd_size: '1'
          - tcd_memory_ptr_id: 'default'
        - transfer_config:
          - 0:
            - uid: '1787886288159'
            - tcdID: 'CH2_TRANSFER0'
            - ssize: 'kEDMA_TransferSize4Bytes'
            - saddr_expr: '&ADC1->RESFIFO'
            - saddr_def: ''
            - soff: '0'
            - soff_def: ''
            - smod: 'kEDMA_ModuloDisable'
            - dsize: 'kEDMA_TransferSize4Bytes'
            - daddr_expr: '&g_adc1DmaBuffer[0]'
            - daddr_def: 'extern volatile uint32_t g_adc1DmaBuffer[6];'
            - doff: 'sizeof(g_adc1DmaBuffer[0])'
            - doff_def: ''
            - dmod: 'kEDMA_ModuloDisable'
            - nbytes: '4'
            - MLconfig:
              - offsetType: 'disabled'
              - mloff: '0'
            - enableChannelLinkMinor: 'false'
            - linkedChannelMinor: '1787886288157'
            - citer: '6'
            - slast: '0'
            - dlast: '-24'
            - enableChannelLinkMajor: 'false'
            - linkedChannelMajor: '1787886288157'
            - submitTransfer: 'true'
        - loopTransfer: 'false'
        - no_init_uid: '1787886288160'
        - init_callback: 'true'
        - callback_function: 'ADC1_DMA_Callback'
        - callback_user_data: ''
        - channel_enabled_interrupts: 'kEDMA_HalfInterruptEnable'
        - interrupt_channel:
          - IRQn: 'DMA_CH2_IRQn'
          - enable_priority: 'true'
          - priority: '3'
      - 1:
        - apiMode: 'trans'
        - edma_channel:
          - channel_prefix_id: 'CH1'
          - uid: '1787989393306'
          - eDMAn: '5'
          - eDMA_source: 'kDma0RequestMuxCtimer1M0'
          - init_channel_priority: 'false'
          - edma_channel_Preemption:
            - enableChannelPreemption: 'false'
            - enablePreemptAbility: 'false'
            - channelPriority: '0'
          - masterIdReplicationEnable: 'noInit'
          - protectionLevel: 'noInit'
          - enable_custom_name: 'false'
        - resetChannel: 'true'
        - enableChannelRequest: 'true'
        - enableAutoStop: 'false'
        - tcd_pool_enable: 'false'
        - tcd_settings:
          - tcd_size: '1'
          - tcd_memory_ptr_id: 'default'
        - transfer_config:
          - 0:
            - uid: '1787989564746'
            - tcdID: 'CH1_TRANSFER0'
            - ssize: 'kEDMA_TransferSize4Bytes'
            - saddr_expr: '&GPIO1->PDIR'
            - saddr_def: ''
            - soff: '0'
            - soff_def: ''
            - smod: 'kEDMA_ModuloDisable'
            - dsize: 'kEDMA_TransferSize4Bytes'
            - daddr_expr: '&g_gpio1SampleBuf[0]'
            - daddr_def: 'extern volatile uint32_t g_gpio1SampleBuf[8];'
            - doff: 'sizeof(g_gpio1SampleBuf[0])'
            - doff_def: ''
            - dmod: 'kEDMA_ModuloDisable'
            - nbytes: '4'
            - MLconfig:
              - offsetType: 'disabled'
              - mloff: '0'
            - enableChannelLinkMinor: 'false'
            - linkedChannelMinor: '1787886288157'
            - citer: '8'
            - slast: '0'
            - dlast: '-32'
            - enableChannelLinkMajor: 'false'
            - linkedChannelMajor: '1787886288157'
            - submitTransfer: 'true'
        - loopTransfer: 'false'
        - no_init_uid: '1787989393318'
        - init_callback: 'true'
        - callback_function: 'GPIO1_SampleDmaCallback'
        - callback_user_data: ''
        - channel_enabled_interrupts: ''
        - interrupt_channel:
          - IRQn: 'DMA_CH5_IRQn'
          - enable_priority: 'true'
          - priority: '3'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
edma_config_t DMA0_config = {
  .enableMasterIdReplication = false,
  .enableGlobalChannelLink = true,
  .enableHaltOnError = true,
  .enableDebugMode = false,
  .enableRoundRobinArbitration = false
};
/* Tansactional transfer configurations */
edma_transfer_config_t DMA0_CH2_Transfers_config[1];
/* Tansactional transfer configurations */
edma_transfer_config_t DMA0_CH1_Transfers_config[1];
edma_handle_t g_adc1DmaHandle;
edma_handle_t DMA0_CH1_Handle;

static void DMA0_init(void) {
  status_t status;
  (void)status;

  /* Channel CH2 initialization */
  /* Set the kDma0RequestMuxAdc1FifoRequest request */
  EDMA_SetChannelMux(DMA0_DMA_BASEADDR, DMA0_CH2_DMA_CHANNEL, DMA0_CH2_DMA_REQUEST);
  /* Create the eDMA g_adc1DmaHandle handle */
  EDMA_CreateHandle(&g_adc1DmaHandle, DMA0_DMA_BASEADDR, DMA0_CH2_DMA_CHANNEL);
  /* DMA0 channel 2 reset */
  EDMA_ResetChannel(DMA0_DMA_BASEADDR, DMA0_CH2_DMA_CHANNEL);
  /* DMA callback initialization */
  EDMA_SetCallback(&g_adc1DmaHandle, ADC1_DMA_Callback, NULL);
  /* DMA0 interrupt request initialization for channel 2 */
  EDMA_EnableChannelInterrupts(DMA0_DMA_BASEADDR, DMA0_CH2_DMA_CHANNEL, DMA0_CH2_IRQ_REQUEST);
  /* Interrupt vector DMA_CH2_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(DMA0_DMA_CH_INT_DONE_2_IRQN, DMA0_DMA_CH_INT_DONE_2_IRQ_PRIORITY);
  /* DMA0 transfer CH2_TRANSFER0 configuration */
  EDMA_PrepareTransferConfig(&DMA0_CH2_TRANSFER0_CONFIG, (void *) &ADC1->RESFIFO, 1 << kEDMA_TransferSize4Bytes, 0, (void *) &g_adc1DmaBuffer[0], 1 << kEDMA_TransferSize4Bytes, sizeof(g_adc1DmaBuffer[0]), 4U, 24U); 
  DMA0_CH2_TRANSFER0_CONFIG.dstMajorLoopOffset = -24;
  /* DMA0 transfer CH2_TRANSFER0 submit */
  status = EDMA_SubmitTransfer(&g_adc1DmaHandle, &DMA0_CH2_TRANSFER0_CONFIG);
  assert(status == kStatus_Success);

  /* Channel CH1 initialization */
  /* Set the kDma0RequestMuxCtimer1M0 request */
  EDMA_SetChannelMux(DMA0_DMA_BASEADDR, DMA0_CH1_DMA_CHANNEL, DMA0_CH1_DMA_REQUEST);
  /* Create the eDMA DMA0_CH1_Handle handle */
  EDMA_CreateHandle(&DMA0_CH1_Handle, DMA0_DMA_BASEADDR, DMA0_CH1_DMA_CHANNEL);
  /* DMA0 channel 5 reset */
  EDMA_ResetChannel(DMA0_DMA_BASEADDR, DMA0_CH1_DMA_CHANNEL);
  /* DMA callback initialization */
  EDMA_SetCallback(&DMA0_CH1_Handle, GPIO1_SampleDmaCallback, NULL);
  /* Interrupt vector DMA_CH5_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(DMA0_DMA_CH_INT_DONE_5_IRQN, DMA0_DMA_CH_INT_DONE_5_IRQ_PRIORITY);
  /* DMA0 transfer CH1_TRANSFER0 configuration */
  EDMA_PrepareTransferConfig(&DMA0_CH1_TRANSFER0_CONFIG, (void *) &GPIO1->PDIR, 1 << kEDMA_TransferSize4Bytes, 0, (void *) &g_gpio1SampleBuf[0], 1 << kEDMA_TransferSize4Bytes, sizeof(g_gpio1SampleBuf[0]), 4U, 32U); 
  DMA0_CH1_TRANSFER0_CONFIG.dstMajorLoopOffset = -32;
  /* DMA0 transfer CH1_TRANSFER0 submit */
  status = EDMA_SubmitTransfer(&DMA0_CH1_Handle, &DMA0_CH1_TRANSFER0_CONFIG);
  assert(status == kStatus_Success);
  /* DMA0 hardware channel 2 request auto stop */
  EDMA_EnableAutoStopRequest(DMA0_DMA_BASEADDR, DMA0_CH2_DMA_CHANNEL, false);
  /* DMA0 channel 2 peripheral request */
  EDMA_EnableChannelRequest(DMA0_DMA_BASEADDR, DMA0_CH2_DMA_CHANNEL);
  /* DMA0 hardware channel 5 request auto stop */
  EDMA_EnableAutoStopRequest(DMA0_DMA_BASEADDR, DMA0_CH1_DMA_CHANNEL, false);
  /* DMA0 channel 5 peripheral request */
  EDMA_EnableChannelRequest(DMA0_DMA_BASEADDR, DMA0_CH1_DMA_CHANNEL);
}

/***********************************************************************************************************************
 * NVIC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table:
      - 0: []
      - 1: []
      - 2: []
      - 3: []
      - 4: []
      - 5: []
      - 6: []
      - 7: []
      - 8: []
    - interrupts:
      - 0:
        - channelId: 'int_0'
        - interrupt_t:
          - IRQn: 'DMA_CH0_IRQn'
          - enable_interrrupt: 'enabled'
          - enable_priority: 'true'
          - priority: '3'
          - enable_custom_name: 'false'
      - 1:
        - channelId: 'int_1'
        - interrupt_t:
          - IRQn: 'DMA_CH1_IRQn'
          - enable_interrrupt: 'enabled'
          - enable_priority: 'true'
          - priority: '3'
          - enable_custom_name: 'false'
      - 2:
        - channelId: 'int_2'
        - interrupt_t:
          - IRQn: 'LPUART1_IRQn'
          - enable_interrrupt: 'enabled'
          - enable_priority: 'true'
          - priority: '3'
          - enable_custom_name: 'false'
      - 3:
        - channelId: 'int_3'
        - interrupt_t:
          - IRQn: 'LPUART2_IRQn'
          - enable_interrrupt: 'enabled'
          - enable_priority: 'true'
          - priority: '3'
          - enable_custom_name: 'false'
      - 4:
        - channelId: 'int_4'
        - interrupt_t:
          - IRQn: 'DMA_CH3_IRQn'
          - enable_interrrupt: 'enabled'
          - enable_priority: 'true'
          - priority: '3'
          - enable_custom_name: 'false'
      - 5:
        - channelId: 'int_5'
        - interrupt_t:
          - IRQn: 'DMA_CH4_IRQn'
          - enable_interrrupt: 'enabled'
          - enable_priority: 'true'
          - priority: '3'
          - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_init(void) {
} */

/***********************************************************************************************************************
 * LPUART1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPUART1'
- type: 'lpuart'
- mode: 'edma'
- custom_name_enabled: 'false'
- type_id: 'lpuart_2.11.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPUART1'
- config_sets:
  - lpuartConfig_t:
    - lpuartConfig:
      - clockSource: 'LpuartClock'
      - lpuartSrcClkFreq: 'ClocksTool_DefaultInit'
      - baudRate_Bps: '115200'
      - parityMode: 'kLPUART_ParityDisabled'
      - dataBitsCount: 'kLPUART_EightDataBits'
      - isMsb: 'false'
      - stopBitCount: 'kLPUART_OneStopBit'
      - enableMatchAddress1: 'false'
      - matchAddress1: '0'
      - enableMatchAddress2: 'false'
      - matchAddress2: '0'
      - txFifoWatermark: '0'
      - rxFifoWatermark: '1'
      - enableRxRTS: 'false'
      - enableTxRTS: 'false'
      - enableTxCTS: 'false'
      - txCtsSource: 'kLPUART_CtsSourcePin'
      - txCtsConfig: 'kLPUART_CtsSampleAtStart'
      - txRtsPolarity: 'kLPUART_RtsPolarityLow'
      - rtsWatermark: '0'
      - rxIdleType: 'kLPUART_IdleTypeStartBit'
      - rxIdleConfig: 'kLPUART_IdleCharacter4'
      - enableTx: 'true'
      - enableRx: 'true'
      - swapTxdRxd: 'false'
      - inverseTxd: 'false'
  - edmaCfg:
    - edma_channels:
      - enable_rx_edma_channel: 'true'
      - edma_rx_channel:
        - uid: '1787886288157'
        - eDMAn: '0'
        - eDMA_source: 'kDma0RequestLPUART1Rx'
        - init_channel_priority: 'false'
        - edma_channel_Preemption:
          - enableChannelPreemption: 'false'
          - enablePreemptAbility: 'false'
          - channelPriority: '0'
        - masterIdReplicationEnable: 'noInit'
        - protectionLevel: 'noInit'
        - enable_custom_name: 'false'
      - enable_tx_edma_channel: 'true'
      - edma_tx_channel:
        - uid: '1787886288154'
        - eDMAn: '1'
        - eDMA_source: 'kDma0RequestLPUART1Tx'
        - init_channel_priority: 'false'
        - edma_channel_Preemption:
          - enableChannelPreemption: 'false'
          - enablePreemptAbility: 'false'
          - channelPriority: '0'
        - masterIdReplicationEnable: 'noInit'
        - protectionLevel: 'noInit'
        - enable_custom_name: 'false'
    - lpuart_edma_handle:
      - enable_custom_name: 'false'
      - init_callback: 'false'
      - callback_fcn: ''
      - user_data: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpuart_config_t LPUART1_config = {
  .baudRate_Bps = 115200UL,
  .parityMode = kLPUART_ParityDisabled,
  .dataBitsCount = kLPUART_EightDataBits,
  .isMsb = false,
  .stopBitCount = kLPUART_OneStopBit,
  .txFifoWatermark = 0U,
  .rxFifoWatermark = 1U,
  .enableRxRTS = false,
  .enableTxRTS = false,
  .enableTxCTS = false,
  .txCtsSource = kLPUART_CtsSourcePin,
  .txCtsConfig = kLPUART_CtsSampleAtStart,
  .txRtsPolarity = kLPUART_RtsPolarityLow,
  .rtsWatermark = 0U,
  .rxIdleType = kLPUART_IdleTypeStartBit,
  .rxIdleConfig = kLPUART_IdleCharacter4,
  .enableTx = true,
  .enableRx = true,
  .swapTxdRxd = false,
  .inverseTxd = false
};
edma_handle_t LPUART1_RX_Handle;
edma_handle_t LPUART1_TX_Handle;
lpuart_edma_handle_t LPUART1_LPUART_eDMA_Handle;

static void LPUART1_init(void) {
  LPUART_Init(LPUART1_PERIPHERAL, &LPUART1_config, LPUART1_CLOCK_SOURCE);
  /* Set the kDma0RequestLPUART1Rx request */
  EDMA_SetChannelMux(LPUART1_RX_DMA_BASEADDR, LPUART1_RX_DMA_CHANNEL, LPUART1_RX_DMA_REQUEST);
  /* Set the kDma0RequestLPUART1Tx request */
  EDMA_SetChannelMux(LPUART1_TX_DMA_BASEADDR, LPUART1_TX_DMA_CHANNEL, LPUART1_TX_DMA_REQUEST);
  /* Create the eDMA LPUART1_RX_Handle handle */
  EDMA_CreateHandle(&LPUART1_RX_Handle, LPUART1_RX_DMA_BASEADDR, LPUART1_RX_DMA_CHANNEL);
  /* Create the eDMA LPUART1_TX_Handle handle */
  EDMA_CreateHandle(&LPUART1_TX_Handle, LPUART1_TX_DMA_BASEADDR, LPUART1_TX_DMA_CHANNEL);
  /* Create the LPUART eDMA handle */
  LPUART_TransferCreateHandleEDMA(LPUART1_PERIPHERAL, &LPUART1_LPUART_eDMA_Handle, NULL, NULL, &LPUART1_TX_Handle, &LPUART1_RX_Handle);
}

/***********************************************************************************************************************
 * CTIMER4 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'CTIMER4'
- type: 'ctimer'
- mode: 'Capture_Match'
- custom_name_enabled: 'false'
- type_id: 'ctimer_2.2.2'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'CTIMER4'
- config_sets:
  - fsl_ctimer:
    - ctimerConfig:
      - mode: 'kCTIMER_TimerMode'
      - clockSource: 'FunctionClock'
      - clockSourceFreq: 'BOARD_BootClockFROHF180M'
      - timerPrescaler: '10 MHz'
    - EnableTimerInInit: 'true'
    - matchChannels:
      - 0:
        - matchChannelPrefixId: 'Match_0'
        - matchChannel: 'kCTIMER_Match_0'
        - matchValueStr: '20 Hz'
        - enableCounterReset: 'true'
        - enableCounterStop: 'false'
        - outControl: 'kCTIMER_Output_NoAction'
        - outPinInitValue: 'low'
        - enableInterrupt: 'false'
    - captureChannels: []
    - interruptCallbackConfig:
      - interrupt:
        - IRQn: 'CTIMER4_IRQn'
        - enable_priority: 'false'
        - priority: '0'
      - callback: 'kCTIMER_NoCallback'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const ctimer_config_t CTIMER4_config = {
  .mode = kCTIMER_TimerMode,
  .input = kCTIMER_Capture_0,
  .prescale = 17
};
const ctimer_match_config_t CTIMER4_Match_0_config = {
  .matchValue = 499999,
  .enableCounterReset = true,
  .enableCounterStop = false,
  .outControl = kCTIMER_Output_NoAction,
  .outPinInitState = false,
  .enableInterrupt = false
};

static void CTIMER4_init(void) {
  /* CTIMER4 peripheral initialization */
  CTIMER_Init(CTIMER4_PERIPHERAL, &CTIMER4_config);
  /* Match channel 0 of CTIMER4 peripheral initialization */
  CTIMER_SetupMatch(CTIMER4_PERIPHERAL, CTIMER4_MATCH_0_CHANNEL, &CTIMER4_Match_0_config);
  /* Start the timer */
  CTIMER_StartTimer(CTIMER4_PERIPHERAL);
}

/***********************************************************************************************************************
 * FLEXPWM0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'FLEXPWM0'
- type: 'pwm'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'pwm_2.6.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FLEXPWM0'
- config_sets:
  - fsl_pwm:
    - clockSource: 'SystemClock'
    - clockSourceFreq: 'ClocksTool_DefaultInit'
    - submodules:
      - 0:
        - sm: 'kPWM_Module_0'
        - sm_id: 'SM0'
        - config:
          - clockSource: 'kPWM_BusClock'
          - prescale: 'kPWM_Prescale_Divide_2'
          - pwmFreq: '2kHz'
          - pairOperation: 'kPWM_Independent'
          - operationMode: 'kPWM_CenterAligned'
          - initializationControl: 'kPWM_Initialize_LocalSync'
          - reloadLogic: 'kPWM_ReloadImmediate'
          - reloadSelect: 'kPWM_LocalReload'
          - reloadFrequency: 'kPWM_LoadEveryOportunity'
          - forceTrigger: 'kPWM_Force_Local'
          - enableDebugMode: 'false'
          - enableWait: 'false'
          - outputTrigger_sel: ''
          - loadOK: 'true'
          - startCounter: 'true'
          - interrupt_sel: ''
          - dma_used: 'false'
          - dma:
            - pwmDMA_activate: 'false'
            - captureDMA_enable: ''
            - captureDMA_source: 'kPWM_DMARequestDisable'
            - captureDMA_watermark_control: 'kPWM_FIFOWatermarksOR'
        - channels:
          - 0:
            - channel_id: 'A'
            - functionSel: 'pwmOutput'
            - pwm:
              - dutyCyclePercent: '50'
              - level: 'kPWM_HighTrue'
              - fault_channel0:
                - dismap: ''
              - faultState: 'kPWM_PwmFaultState0'
              - pwmchannelenable: 'true'
              - deadtime_input_by_force: 'kPWM_UsePwm'
              - clockSource: 'kPWM_BusClock'
              - deadtimeValue: '0'
              - interrupt_sel: ''
          - 1:
            - channel_id: 'B'
            - functionSel: 'notUsed'
          - 2:
            - channel_id: 'X'
            - functionSel: 'notUsed'
        - common_interruptEn: 'false'
        - common_interrupt:
          - IRQn: 'FLEXPWM0_SUBMODULE0_IRQn'
          - enable_interrrupt: 'enabled'
          - enable_priority: 'false'
          - priority: '0'
          - enable_custom_name: 'false'
    - faultChannels:
      - 0:
        - commonFaultSetting:
          - clockSource: 'kPWM_BusClock'
          - faultFilterPeriod: '1'
          - faultFilterCount: '5'
          - faultGlitchStretch: 'false'
        - faults:
          - 0:
            - fault_id: 'Fault0'
            - faultClearingMode: 'kPWM_Automatic'
            - faultLevelR: 'low'
            - enableCombinationalPathR: 'nonFiltered'
            - recoverMode: 'kPWM_NoRecovery'
            - fault_int_source: 'false'
          - 1:
            - fault_id: 'Fault1'
            - faultClearingMode: 'kPWM_Automatic'
            - faultLevelR: 'low'
            - enableCombinationalPathR: 'nonFiltered'
            - recoverMode: 'kPWM_NoRecovery'
            - fault_int_source: 'false'
          - 2:
            - fault_id: 'Fault2'
            - faultClearingMode: 'kPWM_Automatic'
            - faultLevelR: 'low'
            - enableCombinationalPathR: 'nonFiltered'
            - recoverMode: 'kPWM_NoRecovery'
            - fault_int_source: 'false'
          - 3:
            - fault_id: 'Fault3'
            - faultClearingMode: 'kPWM_Automatic'
            - faultLevelR: 'low'
            - enableCombinationalPathR: 'nonFiltered'
            - recoverMode: 'kPWM_NoRecovery'
            - fault_int_source: 'false'
    - fault_interruptEn: 'false'
    - fault_interrupt:
      - IRQn: 'FLEXPWM0_FAULT_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - error_interruptEn: 'false'
    - error_interrupt:
      - IRQn: 'FLEXPWM0_RELOAD_ERROR_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
/* PWM main configuration */
pwm_config_t FLEXPWM0_SM0_config = {
  .clockSource = kPWM_BusClock,
  .prescale = kPWM_Prescale_Divide_2,
  .pairOperation = kPWM_Independent,
  .initializationControl = kPWM_Initialize_LocalSync,
  .reloadLogic = kPWM_ReloadImmediate,
  .reloadSelect = kPWM_LocalReload,
  .reloadFrequency = kPWM_LoadEveryOportunity,
  .forceTrigger = kPWM_Force_Local,
  .enableDebugMode = false,
  .enableWait = false
};

pwm_signal_param_t FLEXPWM0_SM0_pwm_function_config[1]= {
  {
    .pwmChannel = kPWM_PwmA,
    .dutyCyclePercent = 50U,
    .level = kPWM_HighTrue,
    .faultState = kPWM_PwmFaultState0,
    .pwmchannelenable = true,
    .deadtimeValue = 0U
  },
};

const pwm_fault_input_filter_param_t FLEXPWM0_faultInputFilter_config = {
  .faultFilterPeriod = 1U,
  .faultFilterCount = 5U,
  .faultGlitchStretch = false
};
const pwm_fault_param_t FLEXPWM0_Fault0_fault_config = {
  .faultClearingMode = kPWM_Automatic,
  .faultLevel = false,
  .enableCombinationalPath = false,
  .recoverMode = kPWM_NoRecovery
};
const pwm_fault_param_t FLEXPWM0_Fault1_fault_config = {
  .faultClearingMode = kPWM_Automatic,
  .faultLevel = false,
  .enableCombinationalPath = false,
  .recoverMode = kPWM_NoRecovery
};
const pwm_fault_param_t FLEXPWM0_Fault2_fault_config = {
  .faultClearingMode = kPWM_Automatic,
  .faultLevel = false,
  .enableCombinationalPath = false,
  .recoverMode = kPWM_NoRecovery
};
const pwm_fault_param_t FLEXPWM0_Fault3_fault_config = {
  .faultClearingMode = kPWM_Automatic,
  .faultLevel = false,
  .enableCombinationalPath = false,
  .recoverMode = kPWM_NoRecovery
};

static void FLEXPWM0_init(void) {
  /* Initialize PWM submodule SM0 main configuration */
  PWM_Init(FLEXPWM0_PERIPHERAL, FLEXPWM0_SM0, &FLEXPWM0_SM0_config);
  /* Initialize fault input filter configuration */
  PWM_SetupFaultInputFilter(FLEXPWM0_PERIPHERAL, &FLEXPWM0_faultInputFilter_config);
  /* Initialize fault channel 0 fault Fault0 configuration */
  PWM_SetupFaults(FLEXPWM0_PERIPHERAL, FLEXPWM0_F0_FAULT0, &FLEXPWM0_Fault0_fault_config);
  /* Initialize fault channel 0 fault Fault1 configuration */
  PWM_SetupFaults(FLEXPWM0_PERIPHERAL, FLEXPWM0_F0_FAULT1, &FLEXPWM0_Fault1_fault_config);
  /* Initialize fault channel 0 fault Fault2 configuration */
  PWM_SetupFaults(FLEXPWM0_PERIPHERAL, FLEXPWM0_F0_FAULT2, &FLEXPWM0_Fault2_fault_config);
  /* Initialize fault channel 0 fault Fault3 configuration */
  PWM_SetupFaults(FLEXPWM0_PERIPHERAL, FLEXPWM0_F0_FAULT3, &FLEXPWM0_Fault3_fault_config);
  /* Initialize deadtime logic input for the channel A */
  PWM_SetupForceSignal(FLEXPWM0_PERIPHERAL, FLEXPWM0_SM0, FLEXPWM0_SM0_A, kPWM_UsePwm);
  /* Setup PWM output setting for submodule SM0 */
  PWM_SetupPwm(FLEXPWM0_PERIPHERAL, FLEXPWM0_SM0, FLEXPWM0_SM0_pwm_function_config, 1U, kPWM_CenterAligned, FLEXPWM0_SM0_COUNTER_FREQ_HZ, FLEXPWM0_SM0_SM_CLK_SOURCE_FREQ_HZ);
  /* Initialize LDOK for update of the working registers */
  PWM_SetPwmLdok(FLEXPWM0_PERIPHERAL, (kPWM_Control_Module_0), true);
  /* Start selected counters */
  PWM_StartTimer(FLEXPWM0_PERIPHERAL, (kPWM_Control_Module_0));
}

/***********************************************************************************************************************
 * LPUART2 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPUART2'
- type: 'lpuart'
- mode: 'edma'
- custom_name_enabled: 'false'
- type_id: 'lpuart_2.11.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPUART2'
- config_sets:
  - lpuartConfig_t:
    - lpuartConfig:
      - clockSource: 'LpuartClock'
      - lpuartSrcClkFreq: 'ClocksTool_DefaultInit'
      - baudRate_Bps: '115200'
      - parityMode: 'kLPUART_ParityDisabled'
      - dataBitsCount: 'kLPUART_EightDataBits'
      - isMsb: 'false'
      - stopBitCount: 'kLPUART_OneStopBit'
      - enableMatchAddress1: 'false'
      - matchAddress1: '0'
      - enableMatchAddress2: 'false'
      - matchAddress2: '0'
      - txFifoWatermark: '0'
      - rxFifoWatermark: '1'
      - enableRxRTS: 'false'
      - enableTxRTS: 'false'
      - enableTxCTS: 'false'
      - txCtsSource: 'kLPUART_CtsSourcePin'
      - txCtsConfig: 'kLPUART_CtsSampleAtStart'
      - txRtsPolarity: 'kLPUART_RtsPolarityLow'
      - rtsWatermark: '0'
      - rxIdleType: 'kLPUART_IdleTypeStartBit'
      - rxIdleConfig: 'kLPUART_IdleCharacter1'
      - enableTx: 'true'
      - enableRx: 'true'
      - swapTxdRxd: 'false'
      - inverseTxd: 'false'
    - quick_selection: 'QuickSelection1'
  - edmaCfg:
    - edma_channels:
      - enable_rx_edma_channel: 'true'
      - edma_rx_channel:
        - uid: '1787886288161'
        - eDMAn: '3'
        - eDMA_source: 'kDma0RequestLPUART2Rx'
        - init_channel_priority: 'false'
        - edma_channel_Preemption:
          - enableChannelPreemption: 'false'
          - enablePreemptAbility: 'false'
          - channelPriority: '0'
        - masterIdReplicationEnable: 'noInit'
        - protectionLevel: 'noInit'
        - enable_custom_name: 'false'
      - enable_tx_edma_channel: 'true'
      - edma_tx_channel:
        - uid: '1787886288162'
        - eDMAn: '4'
        - eDMA_source: 'kDma0RequestLPUART2Tx'
        - init_channel_priority: 'false'
        - edma_channel_Preemption:
          - enableChannelPreemption: 'false'
          - enablePreemptAbility: 'false'
          - channelPriority: '0'
        - masterIdReplicationEnable: 'noInit'
        - protectionLevel: 'noInit'
        - enable_custom_name: 'false'
    - lpuart_edma_handle:
      - enable_custom_name: 'false'
      - init_callback: 'false'
      - callback_fcn: ''
      - user_data: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpuart_config_t LPUART2_config = {
  .baudRate_Bps = 115200UL,
  .parityMode = kLPUART_ParityDisabled,
  .dataBitsCount = kLPUART_EightDataBits,
  .isMsb = false,
  .stopBitCount = kLPUART_OneStopBit,
  .txFifoWatermark = 0U,
  .rxFifoWatermark = 1U,
  .enableRxRTS = false,
  .enableTxRTS = false,
  .enableTxCTS = false,
  .txCtsSource = kLPUART_CtsSourcePin,
  .txCtsConfig = kLPUART_CtsSampleAtStart,
  .txRtsPolarity = kLPUART_RtsPolarityLow,
  .rtsWatermark = 0U,
  .rxIdleType = kLPUART_IdleTypeStartBit,
  .rxIdleConfig = kLPUART_IdleCharacter1,
  .enableTx = true,
  .enableRx = true,
  .swapTxdRxd = false,
  .inverseTxd = false
};
edma_handle_t LPUART2_RX_Handle;
edma_handle_t LPUART2_TX_Handle;
lpuart_edma_handle_t LPUART2_LPUART_eDMA_Handle;

static void LPUART2_init(void) {
  LPUART_Init(LPUART2_PERIPHERAL, &LPUART2_config, LPUART2_CLOCK_SOURCE);
  /* Set the kDma0RequestLPUART2Rx request */
  EDMA_SetChannelMux(LPUART2_RX_DMA_BASEADDR, LPUART2_RX_DMA_CHANNEL, LPUART2_RX_DMA_REQUEST);
  /* Set the kDma0RequestLPUART2Tx request */
  EDMA_SetChannelMux(LPUART2_TX_DMA_BASEADDR, LPUART2_TX_DMA_CHANNEL, LPUART2_TX_DMA_REQUEST);
  /* Create the eDMA LPUART2_RX_Handle handle */
  EDMA_CreateHandle(&LPUART2_RX_Handle, LPUART2_RX_DMA_BASEADDR, LPUART2_RX_DMA_CHANNEL);
  /* Create the eDMA LPUART2_TX_Handle handle */
  EDMA_CreateHandle(&LPUART2_TX_Handle, LPUART2_TX_DMA_BASEADDR, LPUART2_TX_DMA_CHANNEL);
  /* Create the LPUART eDMA handle */
  LPUART_TransferCreateHandleEDMA(LPUART2_PERIPHERAL, &LPUART2_LPUART_eDMA_Handle, NULL, NULL, &LPUART2_TX_Handle, &LPUART2_RX_Handle);
}

/***********************************************************************************************************************
 * LPUART3 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPUART3'
- type: 'lpuart'
- mode: 'polling'
- custom_name_enabled: 'false'
- type_id: 'lpuart_2.11.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPUART3'
- config_sets:
  - lpuartConfig_t:
    - lpuartConfig:
      - clockSource: 'LpuartClock'
      - lpuartSrcClkFreq: 'ClocksTool_DefaultInit'
      - baudRate_Bps: '115200'
      - parityMode: 'kLPUART_ParityDisabled'
      - dataBitsCount: 'kLPUART_EightDataBits'
      - isMsb: 'false'
      - stopBitCount: 'kLPUART_OneStopBit'
      - enableMatchAddress1: 'false'
      - matchAddress1: '0'
      - enableMatchAddress2: 'false'
      - matchAddress2: '0'
      - txFifoWatermark: '0'
      - rxFifoWatermark: '1'
      - enableRxRTS: 'false'
      - enableTxRTS: 'false'
      - enableTxCTS: 'false'
      - txCtsSource: 'kLPUART_CtsSourcePin'
      - txCtsConfig: 'kLPUART_CtsSampleAtStart'
      - txRtsPolarity: 'kLPUART_RtsPolarityLow'
      - rtsWatermark: '0'
      - rxIdleType: 'kLPUART_IdleTypeStartBit'
      - rxIdleConfig: 'kLPUART_IdleCharacter1'
      - enableTx: 'true'
      - enableRx: 'true'
      - swapTxdRxd: 'false'
      - inverseTxd: 'false'
    - quick_selection: 'QuickSelection1'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpuart_config_t LPUART3_config = {
  .baudRate_Bps = 115200UL,
  .parityMode = kLPUART_ParityDisabled,
  .dataBitsCount = kLPUART_EightDataBits,
  .isMsb = false,
  .stopBitCount = kLPUART_OneStopBit,
  .txFifoWatermark = 0U,
  .rxFifoWatermark = 1U,
  .enableRxRTS = false,
  .enableTxRTS = false,
  .enableTxCTS = false,
  .txCtsSource = kLPUART_CtsSourcePin,
  .txCtsConfig = kLPUART_CtsSampleAtStart,
  .txRtsPolarity = kLPUART_RtsPolarityLow,
  .rtsWatermark = 0U,
  .rxIdleType = kLPUART_IdleTypeStartBit,
  .rxIdleConfig = kLPUART_IdleCharacter1,
  .enableTx = true,
  .enableRx = true,
  .swapTxdRxd = false,
  .inverseTxd = false
};

static void LPUART3_init(void) {
  LPUART_Init(LPUART3_PERIPHERAL, &LPUART3_config, LPUART3_CLOCK_SOURCE);
}

/***********************************************************************************************************************
 * LPUART4 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPUART4'
- type: 'lpuart'
- mode: 'polling'
- custom_name_enabled: 'false'
- type_id: 'lpuart_2.11.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPUART4'
- config_sets:
  - lpuartConfig_t:
    - lpuartConfig:
      - clockSource: 'LpuartClock'
      - lpuartSrcClkFreq: 'ClocksTool_DefaultInit'
      - baudRate_Bps: '115200'
      - parityMode: 'kLPUART_ParityDisabled'
      - dataBitsCount: 'kLPUART_EightDataBits'
      - isMsb: 'false'
      - stopBitCount: 'kLPUART_OneStopBit'
      - enableMatchAddress1: 'false'
      - matchAddress1: '0'
      - enableMatchAddress2: 'false'
      - matchAddress2: '0'
      - txFifoWatermark: '0'
      - rxFifoWatermark: '1'
      - enableRxRTS: 'false'
      - enableTxRTS: 'false'
      - enableTxCTS: 'false'
      - txCtsSource: 'kLPUART_CtsSourcePin'
      - txCtsConfig: 'kLPUART_CtsSampleAtStart'
      - txRtsPolarity: 'kLPUART_RtsPolarityLow'
      - rtsWatermark: '0'
      - rxIdleType: 'kLPUART_IdleTypeStartBit'
      - rxIdleConfig: 'kLPUART_IdleCharacter1'
      - enableTx: 'true'
      - enableRx: 'true'
      - swapTxdRxd: 'false'
      - inverseTxd: 'false'
    - quick_selection: 'QuickSelection1'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpuart_config_t LPUART4_config = {
  .baudRate_Bps = 115200UL,
  .parityMode = kLPUART_ParityDisabled,
  .dataBitsCount = kLPUART_EightDataBits,
  .isMsb = false,
  .stopBitCount = kLPUART_OneStopBit,
  .txFifoWatermark = 0U,
  .rxFifoWatermark = 1U,
  .enableRxRTS = false,
  .enableTxRTS = false,
  .enableTxCTS = false,
  .txCtsSource = kLPUART_CtsSourcePin,
  .txCtsConfig = kLPUART_CtsSampleAtStart,
  .txRtsPolarity = kLPUART_RtsPolarityLow,
  .rtsWatermark = 0U,
  .rxIdleType = kLPUART_IdleTypeStartBit,
  .rxIdleConfig = kLPUART_IdleCharacter1,
  .enableTx = true,
  .enableRx = true,
  .swapTxdRxd = false,
  .inverseTxd = false
};

static void LPUART4_init(void) {
  LPUART_Init(LPUART4_PERIPHERAL, &LPUART4_config, LPUART4_CLOCK_SOURCE);
}

/***********************************************************************************************************************
 * DAC0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'DAC0'
- type: 'dac_1'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'dac_1_2.1.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'DAC0'
- config_sets:
  - fsl_dac:
    - dac_config:
      - fifoWatermarkLevel: '0'
      - fifoTriggerMode: 'kDAC_FIFOTriggerByHardwareMode'
      - fifoWorkMode: 'kDAC_FIFODisabled'
      - referenceVoltageSource: 'kDAC_ReferenceVoltageSourceAlt1'
      - referenceCurrentSource: 'kDAC_ReferenceCurrentSourcePtat'
      - enableOpampBuffer: 'false'
      - periodicTriggerNumber: '0'
      - periodicTriggerWidth: '0'
      - syncTime: '0'
      - enableLowerLowPowerMode: 'false'
    - enable_dma: 'false'
    - dac_dma: 'kDAC_FIFOEmptyDMAEnable'
    - enable_DAC: 'true'
    - enable_convert: 'true'
    - convert_value: '0'
    - interrupt_config:
      - dac_interrupts: ''
      - enable_irq: 'false'
      - interrupt:
        - IRQn: 'DAC0_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const dac_config_t DAC0_config = {
  .fifoWatermarkLevel = 0UL,
  .fifoTriggerMode = kDAC_FIFOTriggerByHardwareMode,
  .fifoWorkMode = kDAC_FIFODisabled,
  .referenceVoltageSource = kDAC_ReferenceVoltageSourceAlt1,
  .referenceCurrentSource = kDAC_ReferenceCurrentSourcePtat,
  .enableOpampBuffer = false,
  .periodicTriggerNumber = 0UL,
  .periodicTriggerWidth = 0UL,
  .syncTime = 0UL,
  .enableLowerLowPowerMode = false,
};

static void DAC0_init(void) {
  /* Power up analog module in SPC */
  SPC_EnableActiveModeAnalogModules(SPC0, kSPC_controlDac0);
  /* Initialize the LPDAC */
  DAC_Init(DAC0_PERIPHERAL, &DAC0_config);
  /* Enable the LPDAC */
  DAC_Enable(DAC0_PERIPHERAL, true);
  /* Set LPDAC value */
  DAC_SetData(DAC0_PERIPHERAL, 0);
}

/***********************************************************************************************************************
 * CRC0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'CRC0'
- type: 'crc'
- mode: 'General'
- custom_name_enabled: 'false'
- type_id: 'crc_2.0.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'CRC0'
- config_sets:
  - fsl_crc:
    - config:
      - polynomial: '0x04C11DB7'
      - seed: '0xFFFFFFFF'
      - reflectIn: 'true'
      - reflectOut: 'true'
      - complementChecksum: 'false'
      - crcBits: 'kCrcBits32'
      - crcResult: 'kCrcFinalChecksum'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const crc_config_t CRC0_config = {
  .polynomial = 0x4C11DB7UL,
  .seed = 0xFFFFFFFFUL,
  .reflectIn = true,
  .reflectOut = true,
  .complementChecksum = false,
  .crcBits = kCrcBits32,
  .crcResult = kCrcFinalChecksum
};

static void CRC0_init(void) {
  CRC_Init(CRC0_PERIPHERAL, &CRC0_config);
}

/***********************************************************************************************************************
 * LPI2C1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPI2C1'
- type: 'lpi2c'
- mode: 'master'
- custom_name_enabled: 'false'
- type_id: 'lpi2c_2.2.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPI2C1'
- config_sets:
  - main:
    - clockSource: 'Lpi2cClock'
    - clockSourceFreq: 'ClocksTool_DefaultInit'
  - interrupt_vector: []
  - master:
    - mode: 'transfer'
    - config:
      - enableMaster: 'true'
      - enableDoze: 'false'
      - debugEnable: 'false'
      - ignoreAck: 'false'
      - pinConfig: 'kLPI2C_2PinOpenDrain'
      - baudRate_Hz: '400000'
      - busIdleTimeout_ns: '0'
      - pinLowTimeout_ns: '0'
      - sdaGlitchFilterWidth_ns: '32'
      - sclGlitchFilterWidth_ns: '32'
      - hostRequest:
        - enable: 'false'
        - source: 'kLPI2C_HostRequestExternalPin'
        - polarity: 'kLPI2C_HostRequestPinActiveHigh'
      - edmaRequestSources: ''
    - transfer:
      - blocking: 'false'
      - enable_custom_handle: 'false'
      - callback:
        - name: ''
        - userData: ''
      - flags: ''
      - slaveAddress: '0'
      - direction: 'kLPI2C_Write'
      - subaddress: '0'
      - subaddressSize: '1'
      - blocking_buffer: 'false'
      - enable_custom_buffer: 'false'
      - dataSize: '1'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpi2c_master_config_t LPI2C1_masterConfig = {
  .enableMaster = true,
  .enableDoze = false,
  .debugEnable = false,
  .ignoreAck = false,
  .pinConfig = kLPI2C_2PinOpenDrain,
  .baudRate_Hz = 400000UL,
  .busIdleTimeout_ns = 0UL,
  .pinLowTimeout_ns = 0UL,
  .sdaGlitchFilterWidth_ns = 32U,
  .sclGlitchFilterWidth_ns = 32U,
  .hostRequest = {
    .enable = false,
    .source = kLPI2C_HostRequestExternalPin,
    .polarity = kLPI2C_HostRequestPinActiveHigh
  }
};
lpi2c_master_transfer_t LPI2C1_masterTransfer = {
  .flags = kLPI2C_TransferDefaultFlag,
  .slaveAddress = 0,
  .direction = kLPI2C_Write,
  .subaddress = 0,
  .subaddressSize = 1,
  .data = LPI2C1_masterBuffer,
  .dataSize = 1
};
lpi2c_master_handle_t LPI2C1_masterHandle;
uint8_t LPI2C1_masterBuffer[LPI2C1_MASTER_BUFFER_SIZE];

static void LPI2C1_init(void) {
  LPI2C_MasterInit(LPI2C1_PERIPHERAL, &LPI2C1_masterConfig, LPI2C1_CLOCK_FREQ);
  LPI2C_MasterTransferCreateHandle(LPI2C1_PERIPHERAL, &LPI2C1_masterHandle, NULL, NULL);
}

/***********************************************************************************************************************
 * LPSPI1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPSPI1'
- type: 'lpspi'
- mode: 'polling'
- custom_name_enabled: 'false'
- type_id: 'lpspi_2.6.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPSPI1'
- config_sets:
  - main:
    - mode: 'kLPSPI_Master'
    - clockSource: 'LpspiClock'
    - clockSourceFreq: 'ClocksTool_DefaultInit'
    - master:
      - baudRate: '25000000'
      - bitsPerFrame: '8'
      - cpol: 'kLPSPI_ClockPolarityActiveHigh'
      - cpha: 'kLPSPI_ClockPhaseFirstEdge'
      - direction: 'kLPSPI_MsbFirst'
      - pcsToSckDelayInNanoSec: '1000'
      - lastSckToPcsDelayInNanoSec: '1000'
      - betweenTransferDelayInNanoSec: '1000'
      - whichPcs: 'kLPSPI_Pcs0'
      - pcsActiveHighOrLow: 'kLPSPI_PcsActiveLow'
      - pinCfg: 'kLPSPI_SdiInSdoOut'
      - pcsFunc: 'kLPSPI_PcsAsCs'
      - dataOutConfig: 'kLpspiDataOutRetained'
      - enableInputDelay: 'false'
    - set_FifoWaterMarks: 'false'
    - fifoWaterMarks:
      - txWatermark: '0'
      - rxWatermark: '0'
    - allPcsPolarityEnable: 'false'
    - allPcsPolarity:
      - kLPSPI_Pcs1Active: 'kLPSPI_PcsActiveLow'
      - kLPSPI_Pcs2Active: 'kLPSPI_PcsActiveLow'
      - kLPSPI_Pcs3Active: 'kLPSPI_PcsActiveLow'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpspi_master_config_t LPSPI1_config = {
  .baudRate = 25000000UL,
  .bitsPerFrame = 8UL,
  .cpol = kLPSPI_ClockPolarityActiveHigh,
  .cpha = kLPSPI_ClockPhaseFirstEdge,
  .direction = kLPSPI_MsbFirst,
  .pcsToSckDelayInNanoSec = 1000UL,
  .lastSckToPcsDelayInNanoSec = 1000UL,
  .betweenTransferDelayInNanoSec = 1000UL,
  .whichPcs = kLPSPI_Pcs0,
  .pcsActiveHighOrLow = kLPSPI_PcsActiveLow,
  .pinCfg = kLPSPI_SdiInSdoOut,
  .pcsFunc = kLPSPI_PcsAsCs,
  .dataOutConfig = kLpspiDataOutRetained,
  .enableInputDelay = false
};

static void LPSPI1_init(void) {
  LPSPI_MasterInit(LPSPI1_PERIPHERAL, &LPSPI1_config, LPSPI1_CLOCK_FREQ);
}

/***********************************************************************************************************************
 * CTIMER0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'CTIMER0'
- type: 'ctimer'
- mode: 'Capture_Match'
- custom_name_enabled: 'false'
- type_id: 'ctimer_2.2.2'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'CTIMER0'
- config_sets:
  - fsl_ctimer:
    - ctimerConfig:
      - mode: 'kCTIMER_TimerMode'
      - clockSource: 'FunctionClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
      - timerPrescaler: '10 MHz'
    - EnableTimerInInit: 'true'
    - matchChannels:
      - 0:
        - matchChannelPrefixId: 'Match_0'
        - matchChannel: 'kCTIMER_Match_0'
        - matchValueStr: '9999'
        - enableCounterReset: 'true'
        - enableCounterStop: 'false'
        - outControl: 'kCTIMER_Output_NoAction'
        - outPinInitValue: 'low'
        - enableInterrupt: 'true'
    - captureChannels: []
    - interruptCallbackConfig:
      - interrupt:
        - IRQn: 'CTIMER0_IRQn'
        - enable_priority: 'true'
        - priority: '7'
      - callback: 'kCTIMER_NoCallback'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const ctimer_config_t CTIMER0_config = {
  .mode = kCTIMER_TimerMode,
  .input = kCTIMER_Capture_0,
  .prescale = 17
};
const ctimer_match_config_t CTIMER0_Match_0_config = {
  .matchValue = 9998,
  .enableCounterReset = true,
  .enableCounterStop = false,
  .outControl = kCTIMER_Output_NoAction,
  .outPinInitState = false,
  .enableInterrupt = true
};

static void CTIMER0_init(void) {
  /* CTIMER0 peripheral initialization */
  CTIMER_Init(CTIMER0_PERIPHERAL, &CTIMER0_config);
  /* Interrupt vector CTIMER0_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(CTIMER0_TIMER_IRQN, CTIMER0_TIMER_IRQ_PRIORITY);
  /* Match channel 0 of CTIMER0 peripheral initialization */
  CTIMER_SetupMatch(CTIMER0_PERIPHERAL, CTIMER0_MATCH_0_CHANNEL, &CTIMER0_Match_0_config);
  /* Start the timer */
  CTIMER_StartTimer(CTIMER0_PERIPHERAL);
}

/***********************************************************************************************************************
 * ADC1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'ADC1'
- type: 'lpadc'
- mode: 'LPADC'
- custom_name_enabled: 'false'
- type_id: 'lpadc_2.8.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'ADC1'
- config_sets:
  - fsl_lpadc:
    - lpadcConfig:
      - clockSource: 'AsynchronousFunctionClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
      - enableJustifiedLeft: 'false'
      - enableInDozeMode: 'true'
      - conversionAverageMode: 'kLPADC_ConversionAverage1'
      - offsetCalibration: 'no'
      - autoCalibrate: 'false'
      - enableAnalogPreliminary: 'false'
      - powerUpDelay: '0x80'
      - referenceVoltageSource: 'kLPADC_ReferenceVoltageAlt1'
      - powerLevelMode: 'kLPADC_PowerLevelAlt1'
      - triggerPriorityPolicy: 'kLPADC_ConvPreemptImmediatelyNotAutoResumed'
      - enableConvPause: 'false'
      - convPauseDelay: '0'
      - FIFOWatermark: '0'
      - FIFOWatermarkDMA: 'true'
    - lpadcConvCommandConfig:
      - 0:
        - user_commandId: 'ADC1_A0'
        - commandId: '1'
        - chainedNextCommandNumber: '2'
        - sampleChannelMode: 'kLPADC_SampleChannelSingleEndSideA'
        - channelNumber: 'A.0'
        - enableAutoChannelIncrement: 'false'
        - loopCount: '0'
        - hardwareAverageMode: 'kLPADC_HardwareAverageCount1'
        - sampleTimeMode: 'kLPADC_SampleTimeADCK3'
        - hardwareCompareMode: 'kLPADC_HardwareCompareDisabled'
        - hardwareCompareValueHigh: '0'
        - hardwareCompareValueLow: '0'
        - conversionResoultuionMode: 'kLPADC_ConversionResolutionStandard'
        - enableWaitTrigger: 'false'
      - 1:
        - user_commandId: 'ADC1_A1'
        - commandId: '2'
        - chainedNextCommandNumber: '3'
        - sampleChannelMode: 'kLPADC_SampleChannelSingleEndSideA'
        - channelNumber: 'A.1'
        - enableAutoChannelIncrement: 'false'
        - loopCount: '0'
        - hardwareAverageMode: 'kLPADC_HardwareAverageCount1'
        - sampleTimeMode: 'kLPADC_SampleTimeADCK3'
        - hardwareCompareMode: 'kLPADC_HardwareCompareDisabled'
        - hardwareCompareValueHigh: '0'
        - hardwareCompareValueLow: '0'
        - conversionResoultuionMode: 'kLPADC_ConversionResolutionStandard'
        - enableWaitTrigger: 'false'
      - 2:
        - user_commandId: 'ADC1_A8'
        - commandId: '3'
        - chainedNextCommandNumber: '4'
        - sampleChannelMode: 'kLPADC_SampleChannelSingleEndSideA'
        - channelNumber: 'A.8'
        - enableAutoChannelIncrement: 'false'
        - loopCount: '0'
        - hardwareAverageMode: 'kLPADC_HardwareAverageCount1'
        - sampleTimeMode: 'kLPADC_SampleTimeADCK3'
        - hardwareCompareMode: 'kLPADC_HardwareCompareDisabled'
        - hardwareCompareValueHigh: '0'
        - hardwareCompareValueLow: '0'
        - conversionResoultuionMode: 'kLPADC_ConversionResolutionStandard'
        - enableWaitTrigger: 'false'
      - 3:
        - user_commandId: 'ADC1_A3'
        - commandId: '4'
        - chainedNextCommandNumber: '5'
        - sampleChannelMode: 'kLPADC_SampleChannelSingleEndSideA'
        - channelNumber: 'A.3'
        - enableAutoChannelIncrement: 'false'
        - loopCount: '0'
        - hardwareAverageMode: 'kLPADC_HardwareAverageCount1'
        - sampleTimeMode: 'kLPADC_SampleTimeADCK3'
        - hardwareCompareMode: 'kLPADC_HardwareCompareDisabled'
        - hardwareCompareValueHigh: '0'
        - hardwareCompareValueLow: '0'
        - conversionResoultuionMode: 'kLPADC_ConversionResolutionStandard'
        - enableWaitTrigger: 'false'
      - 4:
        - user_commandId: 'ADC1_A5'
        - commandId: '5'
        - chainedNextCommandNumber: '6'
        - sampleChannelMode: 'kLPADC_SampleChannelSingleEndSideA'
        - channelNumber: 'A.5'
        - enableAutoChannelIncrement: 'false'
        - loopCount: '0'
        - hardwareAverageMode: 'kLPADC_HardwareAverageCount1'
        - sampleTimeMode: 'kLPADC_SampleTimeADCK3'
        - conversionResoultuionMode: 'kLPADC_ConversionResolutionStandard'
        - enableWaitTrigger: 'false'
      - 5:
        - user_commandId: 'ADC1_A9'
        - commandId: '6'
        - chainedNextCommandNumber: '0'
        - sampleChannelMode: 'kLPADC_SampleChannelSingleEndSideA'
        - channelNumber: 'A.9'
        - enableAutoChannelIncrement: 'false'
        - loopCount: '0'
        - hardwareAverageMode: 'kLPADC_HardwareAverageCount1'
        - sampleTimeMode: 'kLPADC_SampleTimeADCK3'
        - conversionResoultuionMode: 'kLPADC_ConversionResolutionStandard'
        - enableWaitTrigger: 'false'
    - lpadcConvTriggerConfig: []
    - IRQ_cfg:
      - interrupt_type: ''
      - enable_irq: 'false'
      - adc_interrupt:
        - IRQn: 'ADC1_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpadc_config_t ADC1_config = {
  .enableInDozeMode = true,
  .conversionAverageMode = kLPADC_ConversionAverage1,
  .enableAnalogPreliminary = false,
  .powerUpDelay = 0x80UL,
  .referenceVoltageSource = kLPADC_ReferenceVoltageAlt1,
  .powerLevelMode = kLPADC_PowerLevelAlt1,
  .triggerPriorityPolicy = kLPADC_ConvPreemptImmediatelyNotAutoResumed,
  .enableConvPause = false,
  .convPauseDelay = 0UL,
  .FIFOWatermark = 0UL,
};
lpadc_conv_command_config_t ADC1_commandsConfig[6] = {
  {
    .sampleChannelMode = kLPADC_SampleChannelSingleEndSideA,
    .channelNumber = 0U,
    .chainedNextCommandNumber = 2,
    .enableAutoChannelIncrement = false,
    .loopCount = 0UL,
    .hardwareAverageMode = kLPADC_HardwareAverageCount1,
    .sampleTimeMode = kLPADC_SampleTimeADCK3,
    .hardwareCompareMode = kLPADC_HardwareCompareDisabled,
    .hardwareCompareValueHigh = 0UL,
    .hardwareCompareValueLow = 0UL,
    .conversionResolutionMode = kLPADC_ConversionResolutionStandard,
    .enableWaitTrigger = false
  },
  {
    .sampleChannelMode = kLPADC_SampleChannelSingleEndSideA,
    .channelNumber = 1U,
    .chainedNextCommandNumber = 3,
    .enableAutoChannelIncrement = false,
    .loopCount = 0UL,
    .hardwareAverageMode = kLPADC_HardwareAverageCount1,
    .sampleTimeMode = kLPADC_SampleTimeADCK3,
    .hardwareCompareMode = kLPADC_HardwareCompareDisabled,
    .hardwareCompareValueHigh = 0UL,
    .hardwareCompareValueLow = 0UL,
    .conversionResolutionMode = kLPADC_ConversionResolutionStandard,
    .enableWaitTrigger = false
  },
  {
    .sampleChannelMode = kLPADC_SampleChannelSingleEndSideA,
    .channelNumber = 8U,
    .chainedNextCommandNumber = 4,
    .enableAutoChannelIncrement = false,
    .loopCount = 0UL,
    .hardwareAverageMode = kLPADC_HardwareAverageCount1,
    .sampleTimeMode = kLPADC_SampleTimeADCK3,
    .hardwareCompareMode = kLPADC_HardwareCompareDisabled,
    .hardwareCompareValueHigh = 0UL,
    .hardwareCompareValueLow = 0UL,
    .conversionResolutionMode = kLPADC_ConversionResolutionStandard,
    .enableWaitTrigger = false
  },
  {
    .sampleChannelMode = kLPADC_SampleChannelSingleEndSideA,
    .channelNumber = 3U,
    .chainedNextCommandNumber = 5,
    .enableAutoChannelIncrement = false,
    .loopCount = 0UL,
    .hardwareAverageMode = kLPADC_HardwareAverageCount1,
    .sampleTimeMode = kLPADC_SampleTimeADCK3,
    .hardwareCompareMode = kLPADC_HardwareCompareDisabled,
    .hardwareCompareValueHigh = 0UL,
    .hardwareCompareValueLow = 0UL,
    .conversionResolutionMode = kLPADC_ConversionResolutionStandard,
    .enableWaitTrigger = false
  },
  {
    .sampleChannelMode = kLPADC_SampleChannelSingleEndSideA,
    .channelNumber = 5U,
    .chainedNextCommandNumber = 6,
    .enableAutoChannelIncrement = false,
    .loopCount = 0UL,
    .hardwareAverageMode = kLPADC_HardwareAverageCount1,
    .sampleTimeMode = kLPADC_SampleTimeADCK3,
    .conversionResolutionMode = kLPADC_ConversionResolutionStandard,
    .enableWaitTrigger = false
  },
  {
    .sampleChannelMode = kLPADC_SampleChannelSingleEndSideA,
    .channelNumber = 9U,
    .chainedNextCommandNumber = 0,
    .enableAutoChannelIncrement = false,
    .loopCount = 0UL,
    .hardwareAverageMode = kLPADC_HardwareAverageCount1,
    .sampleTimeMode = kLPADC_SampleTimeADCK3,
    .conversionResolutionMode = kLPADC_ConversionResolutionStandard,
    .enableWaitTrigger = false
  }
};

static void ADC1_init(void) {
  /* Initialize LPADC converter */
  LPADC_Init(ADC1_PERIPHERAL, &ADC1_config);
  /* Enable DMA request on FIFO watermark event */
  LPADC_EnableFIFOWatermarkDMA(ADC1_PERIPHERAL, true);
  /* Configure conversion command 1. */
  LPADC_SetConvCommandConfig(ADC1_PERIPHERAL, ADC1_ADC1_A0, &ADC1_commandsConfig[0]);
  /* Configure conversion command 2. */
  LPADC_SetConvCommandConfig(ADC1_PERIPHERAL, ADC1_ADC1_A1, &ADC1_commandsConfig[1]);
  /* Configure conversion command 3. */
  LPADC_SetConvCommandConfig(ADC1_PERIPHERAL, ADC1_ADC1_A8, &ADC1_commandsConfig[2]);
  /* Configure conversion command 4. */
  LPADC_SetConvCommandConfig(ADC1_PERIPHERAL, ADC1_ADC1_A3, &ADC1_commandsConfig[3]);
  /* Configure conversion command 5. */
  LPADC_SetConvCommandConfig(ADC1_PERIPHERAL, ADC1_ADC1_A5, &ADC1_commandsConfig[4]);
  /* Configure conversion command 6. */
  LPADC_SetConvCommandConfig(ADC1_PERIPHERAL, ADC1_ADC1_A9, &ADC1_commandsConfig[5]);
}

/***********************************************************************************************************************
 * GPIO0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIO0'
- type: 'gpio_adapter'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'gpio_adapter_1.0.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIO0'
- config_sets:
  - fsl_adapter_gpio:
    - signalsFilter: 'default boot'
    - gpioSignalsParameters:
      - 0: []
      - 1: []
      - 2: []
      - 3: []
      - 4: []
    - gpioPinsOverView:
      - 0: []
      - 1: []
      - 2: []
      - 3: []
      - 4: []
    - gpioPinsConfig: []
    - globalCfg: []
    - differentPeripheralsAdd: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
/* Get GPIO pin configuration */
hal_gpio_pin_config_t createAdapterGpioPinConfig(GPIO_Type *port, uint8_t pin, hal_gpio_direction_t direction, uint8_t level){
  hal_gpio_pin_config_t temp;
  /* Array of GPIO peripheral base address. */
  static GPIO_Type *const s_gpioBases[] = GPIO_BASE_PTRS;
  uint8_t portInd;
  /* Find the port index from base address mappings. */
  for (portInd = 0U; portInd < ARRAY_SIZE(s_gpioBases); portInd++)
  {    if (s_gpioBases[portInd] == port)
    {
      break;
    }
  }
  
  assert(portInd < ARRAY_SIZE(s_gpioBases));
  
  temp.direction = direction;
  temp.level = level;
  temp.port = portInd;
  temp.pin = pin;
  
  return temp;
};
GPIO_HANDLE_DEFINE(BOARD_INITPINS_OUTPUT_KEY_O1_handle);
GPIO_HANDLE_DEFINE(BOARD_INITPINS_OUTPUT_KEY_O2_handle);
GPIO_HANDLE_DEFINE(BOARD_INITPINS_OUTPUT_KEY_O3_handle);
GPIO_HANDLE_DEFINE(BOARD_INITPINS_OUTPUT_KEY_O4_handle);
GPIO_HANDLE_DEFINE(BOARD_INITPINS_OUTPUT_KEY_O5_handle);

static void GPIO0_init(void) {
  /* GPIO adapter initialization */
  static hal_gpio_pin_config_t gpioPinConfig;
  hal_gpio_status_t status;
  (void)status; // suppress warning in the run configuration
  /* GPIO, 2 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITPINS_OUTPUT_KEY_O1_GPIO, BOARD_INITPINS_OUTPUT_KEY_O1_PIN, BOARD_INITPINS_OUTPUT_KEY_O1_PIN_DIRECTION, BOARD_INITPINS_OUTPUT_KEY_O1_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITPINS_OUTPUT_KEY_O1_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* GPIO, 3 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITPINS_OUTPUT_KEY_O2_GPIO, BOARD_INITPINS_OUTPUT_KEY_O2_PIN, BOARD_INITPINS_OUTPUT_KEY_O2_PIN_DIRECTION, BOARD_INITPINS_OUTPUT_KEY_O2_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITPINS_OUTPUT_KEY_O2_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* GPIO, 6 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITPINS_OUTPUT_KEY_O3_GPIO, BOARD_INITPINS_OUTPUT_KEY_O3_PIN, BOARD_INITPINS_OUTPUT_KEY_O3_PIN_DIRECTION, BOARD_INITPINS_OUTPUT_KEY_O3_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITPINS_OUTPUT_KEY_O3_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* GPIO, 16 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITPINS_OUTPUT_KEY_O4_GPIO, BOARD_INITPINS_OUTPUT_KEY_O4_PIN, BOARD_INITPINS_OUTPUT_KEY_O4_PIN_DIRECTION, BOARD_INITPINS_OUTPUT_KEY_O4_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITPINS_OUTPUT_KEY_O4_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* GPIO, 17 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITPINS_OUTPUT_KEY_O5_GPIO, BOARD_INITPINS_OUTPUT_KEY_O5_PIN, BOARD_INITPINS_OUTPUT_KEY_O5_PIN_DIRECTION, BOARD_INITPINS_OUTPUT_KEY_O5_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITPINS_OUTPUT_KEY_O5_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
}

/***********************************************************************************************************************
 * GPIO1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIO1'
- type: 'gpio_adapter'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'gpio_adapter_1.0.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIO1'
- config_sets:
  - fsl_adapter_gpio:
    - signalsFilter: 'default boot'
    - gpioSignalsParameters:
      - 0: []
      - 1: []
      - 2: []
      - 3: []
      - 4: []
      - 5: []
      - 6: []
      - 7: []
    - gpioPinsOverView:
      - 0: []
      - 1: []
      - 2: []
      - 3: []
      - 4: []
      - 5: []
      - 6: []
      - 7: []
    - gpioPinsConfig: []
    - globalCfg: []
    - differentPeripheralsAdd: []
    - quick_selection: 'QuickSelection1'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
GPIO_HANDLE_DEFINE(BOARD_INITPINS_INPUT_IN1_handle);
GPIO_HANDLE_DEFINE(BOARD_INITPINS_INPUT_IN10_handle);
GPIO_HANDLE_DEFINE(BOARD_INITPINS_INPUT_KEY6_handle);
GPIO_HANDLE_DEFINE(BOARD_INITPINS_INPUT_KEY5_handle);
GPIO_HANDLE_DEFINE(BOARD_INITPINS_INPUT_KEY4_handle);
GPIO_HANDLE_DEFINE(BOARD_INITPINS_INPUT_KEY3_handle);
GPIO_HANDLE_DEFINE(BOARD_INITPINS_INPUT_KEY2_handle);
GPIO_HANDLE_DEFINE(BOARD_INITPINS_INPUT_IN5_handle);

static void GPIO1_init(void) {
  /* GPIO adapter initialization */
  static hal_gpio_pin_config_t gpioPinConfig;
  hal_gpio_status_t status;
  (void)status; // suppress warning in the run configuration
  /* GPIO, 0 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITPINS_INPUT_IN1_GPIO, BOARD_INITPINS_INPUT_IN1_PIN, BOARD_INITPINS_INPUT_IN1_PIN_DIRECTION, BOARD_INITPINS_INPUT_IN1_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITPINS_INPUT_IN1_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* GPIO, 1 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITPINS_INPUT_IN10_GPIO, BOARD_INITPINS_INPUT_IN10_PIN, BOARD_INITPINS_INPUT_IN10_PIN_DIRECTION, BOARD_INITPINS_INPUT_IN10_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITPINS_INPUT_IN10_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* GPIO, 2 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITPINS_INPUT_KEY6_GPIO, BOARD_INITPINS_INPUT_KEY6_PIN, BOARD_INITPINS_INPUT_KEY6_PIN_DIRECTION, BOARD_INITPINS_INPUT_KEY6_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITPINS_INPUT_KEY6_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* GPIO, 3 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITPINS_INPUT_KEY5_GPIO, BOARD_INITPINS_INPUT_KEY5_PIN, BOARD_INITPINS_INPUT_KEY5_PIN_DIRECTION, BOARD_INITPINS_INPUT_KEY5_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITPINS_INPUT_KEY5_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* GPIO, 4 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITPINS_INPUT_KEY4_GPIO, BOARD_INITPINS_INPUT_KEY4_PIN, BOARD_INITPINS_INPUT_KEY4_PIN_DIRECTION, BOARD_INITPINS_INPUT_KEY4_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITPINS_INPUT_KEY4_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* GPIO, 5 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITPINS_INPUT_KEY3_GPIO, BOARD_INITPINS_INPUT_KEY3_PIN, BOARD_INITPINS_INPUT_KEY3_PIN_DIRECTION, BOARD_INITPINS_INPUT_KEY3_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITPINS_INPUT_KEY3_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* GPIO, 6 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITPINS_INPUT_KEY2_GPIO, BOARD_INITPINS_INPUT_KEY2_PIN, BOARD_INITPINS_INPUT_KEY2_PIN_DIRECTION, BOARD_INITPINS_INPUT_KEY2_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITPINS_INPUT_KEY2_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* GPIO, 7 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITPINS_INPUT_IN5_GPIO, BOARD_INITPINS_INPUT_IN5_PIN, BOARD_INITPINS_INPUT_IN5_PIN_DIRECTION, BOARD_INITPINS_INPUT_IN5_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITPINS_INPUT_IN5_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
}

/***********************************************************************************************************************
 * CTIMER1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'CTIMER1'
- type: 'ctimer'
- mode: 'Capture_Match'
- custom_name_enabled: 'false'
- type_id: 'ctimer_2.2.2'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'CTIMER1'
- config_sets:
  - fsl_ctimer:
    - ctimerConfig:
      - mode: 'kCTIMER_TimerMode'
      - clockSource: 'FunctionClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
      - timerPrescaler: '10 MHz'
    - EnableTimerInInit: 'true'
    - matchChannels:
      - 0:
        - matchChannelPrefixId: 'Match_0'
        - matchChannel: 'kCTIMER_Match_0'
        - matchValueStr: '1000'
        - enableCounterReset: 'true'
        - enableCounterStop: 'false'
        - outControl: 'kCTIMER_Output_NoAction'
        - outPinInitValue: 'low'
        - enableInterrupt: 'false'
    - captureChannels: []
    - interruptCallbackConfig:
      - interrupt:
        - IRQn: 'CTIMER1_IRQn'
        - enable_priority: 'false'
        - priority: '0'
      - callback: 'kCTIMER_NoCallback'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const ctimer_config_t CTIMER1_config = {
  .mode = kCTIMER_TimerMode,
  .input = kCTIMER_Capture_0,
  .prescale = 17
};
const ctimer_match_config_t CTIMER1_Match_0_config = {
  .matchValue = 999,
  .enableCounterReset = true,
  .enableCounterStop = false,
  .outControl = kCTIMER_Output_NoAction,
  .outPinInitState = false,
  .enableInterrupt = false
};

static void CTIMER1_init(void) {
  /* CTIMER1 peripheral initialization */
  CTIMER_Init(CTIMER1_PERIPHERAL, &CTIMER1_config);
  /* Match channel 0 of CTIMER1 peripheral initialization */
  CTIMER_SetupMatch(CTIMER1_PERIPHERAL, CTIMER1_MATCH_0_CHANNEL, &CTIMER1_Match_0_config);
  /* Start the timer */
  CTIMER_StartTimer(CTIMER1_PERIPHERAL);
}

/***********************************************************************************************************************
 * RTC0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'RTC0'
- type: 'rtc'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'rtc_2.4.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'RTC0'
- config_sets:
  - fsl_rtc:
    - clockConfig_t:
      - clockSource: 'clk_16khz'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
    - rtc_config:
      - updateMode: 'false'
      - supervisorAccess: 'false'
      - compensationIntervalInt: '1'
      - compensationTimeInt: '0'
      - setDateTime: 'true'
      - rtc_datetime:
        - year: '2026'
        - month: '8'
        - day: '29'
        - hour: '12'
        - minute: '12'
        - second: '0'
      - setAlarm: 'false'
      - alarm_datetime:
        - year: '1970'
        - month: '1'
        - day: '1'
        - hour: '0'
        - minute: '0'
        - second: '0'
      - start: 'false'
    - interruptsCfg:
      - interruptSources: ''
      - isSecondsInterruptEnabled: 'false'
      - secondsInterrupt:
        - IRQn: 'RTC_1HZ_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '1'
        - enable_custom_name: 'false'
      - isInterruptEnabled: 'false'
      - commonInterrupt:
        - IRQn: 'RTC_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const rtc_config_t RTC0_config = {
  .wakeupSelect = false,
  .updateMode = false,
  .supervisorAccess = false,
  .compensationInterval = 0x0U,
  .compensationTime = 0x0U
};
rtc_datetime_t RTC0_dateTimeStruct = {
  .year = 2026U,
  .month = 8U,
  .day = 29U,
  .hour = 12U,
  .minute = 12U,
  .second = 0U
};

static void RTC0_init(void) {
  /* RTC initialization */
  RTC_Init(RTC0_PERIPHERAL, &RTC0_config);
  /* Set LPO 16kHz clock source */
  RTC_EnableLPOClock(RTC0_PERIPHERAL, true);
  /* Stop RTC timer */
  RTC_StopTimer(RTC0_PERIPHERAL);
  /* Date and time initialization */
  RTC_SetDatetime(RTC0_PERIPHERAL, &RTC0_dateTimeStruct);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
static void BOARD_InitPeripherals_CommonPostInit(void)
{
  /* Interrupt vector DMA_CH0_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(INT_0_IRQN, INT_0_IRQ_PRIORITY);
  /* Interrupt vector DMA_CH1_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(INT_1_IRQN, INT_1_IRQ_PRIORITY);
  /* Interrupt vector LPUART1_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(INT_2_IRQN, INT_2_IRQ_PRIORITY);
  /* Interrupt vector LPUART2_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(INT_3_IRQN, INT_3_IRQ_PRIORITY);
  /* Interrupt vector DMA_CH3_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(INT_4_IRQN, INT_4_IRQ_PRIORITY);
  /* Interrupt vector DMA_CH4_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(INT_5_IRQN, INT_5_IRQ_PRIORITY);
  /* Enable interrupt INT_0_IRQN request in the NVIC */
  EnableIRQ(INT_0_IRQN);
  /* Enable interrupt INT_1_IRQN request in the NVIC */
  EnableIRQ(INT_1_IRQN);
  /* Enable interrupt INT_2_IRQN request in the NVIC */
  EnableIRQ(INT_2_IRQN);
  /* Enable interrupt INT_3_IRQN request in the NVIC */
  EnableIRQ(INT_3_IRQN);
  /* Enable interrupt INT_4_IRQN request in the NVIC */
  EnableIRQ(INT_4_IRQN);
  /* Enable interrupt INT_5_IRQN request in the NVIC */
  EnableIRQ(INT_5_IRQN);
}

void BOARD_InitPeripherals(void)
{
  /* Global initialization */
  (void)memset(DMA0_config.channelConfig, 0, FSL_FEATURE_EDMA_INSTANCE_CHANNELn(DMA0_DMA_BASEADDR) * sizeof(edma_channel_config_t *));
  EDMA_Init(DMA0_DMA_BASEADDR, &DMA0_config);
  /* GPIO adapter pre-initialization */
  HAL_GpioPreInit();

  /* Initialize components */
  DMA0_init();
  LPUART1_init();
  CTIMER4_init();
  FLEXPWM0_init();
  LPUART2_init();
  LPUART3_init();
  LPUART4_init();
  DAC0_init();
  CRC0_init();
  LPI2C1_init();
  LPSPI1_init();
  CTIMER0_init();
  ADC1_init();
  GPIO0_init();
  GPIO1_init();
  CTIMER1_init();
  RTC0_init();
  /* Common post-initialization */
  BOARD_InitPeripherals_CommonPostInit();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
