/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_edma.h"
#include "stdlib.h"
#include "fsl_common.h"
#include "fsl_lpuart.h"
#include "fsl_clock.h"
#include "fsl_lpuart_edma.h"
#include "fsl_ctimer.h"
#include "fsl_pwm.h"
#include "fsl_spc.h"
#include "fsl_dac.h"
#include "fsl_crc.h"
#include "fsl_lpi2c.h"
#include "fsl_lpspi.h"
#include "fsl_lpadc.h"
#include "fsl_adapter_gpio.h"
#include "pin_mux.h"
#include "fsl_rtc.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Used DMA device. */
#define DMA0_DMA_BASEADDR (EDMA_Type *)DMA0

  /* Channel CH2 definitions */
/* DMA0 eDMA source request. */
#define DMA0_CH2_DMA_REQUEST kDma0RequestMuxAdc1FifoRequest
/* Selected eDMA channel number. */
#define DMA0_CH2_DMA_CHANNEL 2
/* TCD pool size */
#define DMA0_CH2_TCD_SIZE 1
/* DMA0 interrupt vector ID (number). */
#define DMA0_DMA_CH_INT_DONE_2_IRQN DMA_CH2_IRQn
/* DMA0 interrupt vector priority. */
#define DMA0_DMA_CH_INT_DONE_2_IRQ_PRIORITY 3
/* DMA0 channel interrupt request. */
#define DMA0_CH2_IRQ_REQUEST kEDMA_HalfInterruptEnable
/* Transfer structure index 0 definition */
#define DMA0_CH2_TRANSFER0_CONFIG DMA0_CH2_Transfers_config[0]

  /* Channel CH1 definitions */
/* DMA0 eDMA source request. */
#define DMA0_CH1_DMA_REQUEST kDma0RequestMuxCtimer1M0
/* Selected eDMA channel number. */
#define DMA0_CH1_DMA_CHANNEL 5
/* TCD pool size */
#define DMA0_CH1_TCD_SIZE 1
/* DMA0 interrupt vector ID (number). */
#define DMA0_DMA_CH_INT_DONE_5_IRQN DMA_CH5_IRQn
/* DMA0 interrupt vector priority. */
#define DMA0_DMA_CH_INT_DONE_5_IRQ_PRIORITY 3
/* Transfer structure index 0 definition */
#define DMA0_CH1_TRANSFER0_CONFIG DMA0_CH1_Transfers_config[0]
/* NVIC interrupt vector ID (number). */
#define INT_0_IRQN DMA_CH0_IRQn
/* NVIC interrupt vector priority. */
#define INT_0_IRQ_PRIORITY 3
/* NVIC interrupt handler identifier. */
#define INT_0_IRQHANDLER DMA_CH0_IRQHandler
/* NVIC interrupt vector ID (number). */
#define INT_1_IRQN DMA_CH1_IRQn
/* NVIC interrupt vector priority. */
#define INT_1_IRQ_PRIORITY 3
/* NVIC interrupt handler identifier. */
#define INT_1_IRQHANDLER DMA_CH1_IRQHandler
/* NVIC interrupt vector ID (number). */
#define INT_2_IRQN LPUART1_IRQn
/* NVIC interrupt vector priority. */
#define INT_2_IRQ_PRIORITY 3
/* NVIC interrupt handler identifier. */
#define INT_2_IRQHANDLER LPUART1_IRQHandler
/* NVIC interrupt vector ID (number). */
#define INT_3_IRQN LPUART2_IRQn
/* NVIC interrupt vector priority. */
#define INT_3_IRQ_PRIORITY 3
/* NVIC interrupt handler identifier. */
#define INT_3_IRQHANDLER LPUART2_IRQHandler
/* NVIC interrupt vector ID (number). */
#define INT_4_IRQN DMA_CH3_IRQn
/* NVIC interrupt vector priority. */
#define INT_4_IRQ_PRIORITY 3
/* NVIC interrupt handler identifier. */
#define INT_4_IRQHANDLER DMA_CH3_IRQHandler
/* NVIC interrupt vector ID (number). */
#define INT_5_IRQN DMA_CH4_IRQn
/* NVIC interrupt vector priority. */
#define INT_5_IRQ_PRIORITY 3
/* NVIC interrupt handler identifier. */
#define INT_5_IRQHANDLER DMA_CH4_IRQHandler
/* Definition of peripheral ID */
#define LPUART1_PERIPHERAL LPUART1
/* Definition of the clock source frequency */
#define LPUART1_CLOCK_SOURCE 180000000UL
/* LPUART1 eDMA source request. */
#define LPUART1_RX_DMA_REQUEST kDma0RequestLPUART1Rx
/* Selected eDMA channel number. */
#define LPUART1_RX_DMA_CHANNEL 0
/* Used DMA device. */
#define LPUART1_RX_DMA_BASEADDR DMA0
/* LPUART1 eDMA source request. */
#define LPUART1_TX_DMA_REQUEST kDma0RequestLPUART1Tx
/* Selected eDMA channel number. */
#define LPUART1_TX_DMA_CHANNEL 1
/* Used DMA device. */
#define LPUART1_TX_DMA_BASEADDR DMA0
/* Definition of peripheral ID */
#define CTIMER4_PERIPHERAL CTIMER4
/* Timer tick frequency in Hz (input frequency of the timer) */
#define CTIMER4_TICK_FREQ 10000000UL
/* Timer tick period in ns (input period of the timer) */
#define CTIMER4_TICK_PERIOD 100UL
/* Definition of PWM period channel. */
#define CTIMER4_PWM_PERIOD_CH kCTIMER_Match_0
/* Definition of channel 0 ID */
#define CTIMER4_MATCH_0_CHANNEL kCTIMER_Match_0
/* Definition of peripheral ID */
#define FLEXPWM0_PERIPHERAL FLEXPWM0
/* Definition of submodule 0 ID */
#define FLEXPWM0_SM0 kPWM_Module_0
/* Definition of clock source of submodule 0 frequency in Hertz */
#define FLEXPWM0_SM0_SM_CLK_SOURCE_FREQ_HZ 180000000U
/* Definition of submodule 0 counter clock source frequency in Hertz - FLEXPWM0_SM0_SM_CLK_SOURCE_FREQ_HZ divided by prescaler */
#define FLEXPWM0_SM0_COUNTER_CLK_SOURCE_FREQ_HZ 90000000U
/* Definition of submodule 0 counter (PWM) frequency in Hertz */
#define FLEXPWM0_SM0_COUNTER_FREQ_HZ 2000U
/* Definition of submodule 0 channel A ID */
#define FLEXPWM0_SM0_A kPWM_PwmA
/* Definition of submodule 0 channel B ID */
#define FLEXPWM0_SM0_B kPWM_PwmB
/* Definition of submodule 0 channel X ID */
#define FLEXPWM0_SM0_X kPWM_PwmX
/* Definition of fault Fault0 ID */
#define FLEXPWM0_F0_FAULT0 kPWM_Fault_0
/* Definition of fault Fault1 ID */
#define FLEXPWM0_F0_FAULT1 kPWM_Fault_1
/* Definition of fault Fault2 ID */
#define FLEXPWM0_F0_FAULT2 kPWM_Fault_2
/* Definition of fault Fault3 ID */
#define FLEXPWM0_F0_FAULT3 kPWM_Fault_3
/* Definition of peripheral ID */
#define LPUART2_PERIPHERAL LPUART2
/* Definition of the clock source frequency */
#define LPUART2_CLOCK_SOURCE 180000000UL
/* LPUART2 eDMA source request. */
#define LPUART2_RX_DMA_REQUEST kDma0RequestLPUART2Rx
/* Selected eDMA channel number. */
#define LPUART2_RX_DMA_CHANNEL 3
/* Used DMA device. */
#define LPUART2_RX_DMA_BASEADDR DMA0
/* LPUART2 eDMA source request. */
#define LPUART2_TX_DMA_REQUEST kDma0RequestLPUART2Tx
/* Selected eDMA channel number. */
#define LPUART2_TX_DMA_CHANNEL 4
/* Used DMA device. */
#define LPUART2_TX_DMA_BASEADDR DMA0
/* Definition of peripheral ID */
#define LPUART3_PERIPHERAL LPUART3
/* Definition of the clock source frequency */
#define LPUART3_CLOCK_SOURCE 180000000UL
/* Definition of peripheral ID */
#define LPUART4_PERIPHERAL LPUART4
/* Definition of the clock source frequency */
#define LPUART4_CLOCK_SOURCE 180000000UL
/* BOARD_InitPeripherals defines for DAC0 */
/* Definition of peripheral ID */
#define DAC0_PERIPHERAL DAC0
/* DAC0 interrupt vector ID (number). */
#define DAC0_IRQN DAC0_IRQn
/* DAC0 interrupt handler identifier. */
#define DAC0_IRQHANDLER DAC0_IRQHandler
/* CRC base */
#define CRC0_PERIPHERAL CRC0
/* BOARD_InitPeripherals defines for LPI2C1 */
/* Definition of peripheral ID */
#define LPI2C1_PERIPHERAL LPI2C1
/* Definition of clock source */
#define LPI2C1_CLOCK_FREQ 60000000UL
/* Transfer buffer size */
#define LPI2C1_MASTER_BUFFER_SIZE 1
/* Definition of follower address */
#define LPI2C1_MASTER_SLAVE_ADDRESS 0
/* BOARD_InitPeripherals defines for LPSPI1 */
/* Definition of peripheral ID */
#define LPSPI1_PERIPHERAL LPSPI1
/* Definition of clock source */
#define LPSPI1_CLOCK_FREQ 90000000UL
/* Definition of peripheral ID */
#define CTIMER0_PERIPHERAL CTIMER0
/* Timer tick frequency in Hz (input frequency of the timer) */
#define CTIMER0_TICK_FREQ 10000000UL
/* Timer tick period in ns (input period of the timer) */
#define CTIMER0_TICK_PERIOD 100UL
/* Definition of PWM period channel. */
#define CTIMER0_PWM_PERIOD_CH kCTIMER_Match_0
/* Definition of channel 0 ID */
#define CTIMER0_MATCH_0_CHANNEL kCTIMER_Match_0
/* CTIMER0 interrupt vector ID (number). */
#define CTIMER0_TIMER_IRQN CTIMER0_IRQn
/* CTIMER0 interrupt vector priority. */
#define CTIMER0_TIMER_IRQ_PRIORITY 7
/* Alias for ADC1 peripheral */
#define ADC1_PERIPHERAL ADC1
/* Command 1 - ADC1_A0 */
#define ADC1_ADC1_A0 1U
/* Command 2 - ADC1_A1 */
#define ADC1_ADC1_A1 2U
/* Command 3 - ADC1_A8 */
#define ADC1_ADC1_A8 3U
/* Command 4 - ADC1_A3 */
#define ADC1_ADC1_A3 4U
/* Command 5 - ADC1_A5 */
#define ADC1_ADC1_A5 5U
/* Command 6 - ADC1_A9 */
#define ADC1_ADC1_A9 6U
/* GPIO, 2 signal defines */
/* Definition of the pin direction */
#define BOARD_INITPINS_OUTPUT_KEY_O1_PIN_DIRECTION kHAL_GpioDirectionOut
/* Definition of the pin level after initialization */
#define BOARD_INITPINS_OUTPUT_KEY_O1_PIN_LEVEL 0U
/* GPIO, 3 signal defines */
/* Definition of the pin direction */
#define BOARD_INITPINS_OUTPUT_KEY_O2_PIN_DIRECTION kHAL_GpioDirectionOut
/* Definition of the pin level after initialization */
#define BOARD_INITPINS_OUTPUT_KEY_O2_PIN_LEVEL 0U
/* GPIO, 6 signal defines */
/* Definition of the pin direction */
#define BOARD_INITPINS_OUTPUT_KEY_O3_PIN_DIRECTION kHAL_GpioDirectionOut
/* Definition of the pin level after initialization */
#define BOARD_INITPINS_OUTPUT_KEY_O3_PIN_LEVEL 0U
/* GPIO, 16 signal defines */
/* Definition of the pin direction */
#define BOARD_INITPINS_OUTPUT_KEY_O4_PIN_DIRECTION kHAL_GpioDirectionOut
/* Definition of the pin level after initialization */
#define BOARD_INITPINS_OUTPUT_KEY_O4_PIN_LEVEL 0U
/* GPIO, 17 signal defines */
/* Definition of the pin direction */
#define BOARD_INITPINS_OUTPUT_KEY_O5_PIN_DIRECTION kHAL_GpioDirectionOut
/* Definition of the pin level after initialization */
#define BOARD_INITPINS_OUTPUT_KEY_O5_PIN_LEVEL 0U
/* GPIO, 0 signal defines */
/* Definition of the pin direction */
#define BOARD_INITPINS_INPUT_IN1_PIN_DIRECTION kHAL_GpioDirectionIn
/* Definition of the pin level after initialization */
#define BOARD_INITPINS_INPUT_IN1_PIN_LEVEL 0U
/* GPIO, 1 signal defines */
/* Definition of the pin direction */
#define BOARD_INITPINS_INPUT_IN10_PIN_DIRECTION kHAL_GpioDirectionIn
/* Definition of the pin level after initialization */
#define BOARD_INITPINS_INPUT_IN10_PIN_LEVEL 0U
/* GPIO, 2 signal defines */
/* Definition of the pin direction */
#define BOARD_INITPINS_INPUT_KEY6_PIN_DIRECTION kHAL_GpioDirectionIn
/* Definition of the pin level after initialization */
#define BOARD_INITPINS_INPUT_KEY6_PIN_LEVEL 0U
/* GPIO, 3 signal defines */
/* Definition of the pin direction */
#define BOARD_INITPINS_INPUT_KEY5_PIN_DIRECTION kHAL_GpioDirectionIn
/* Definition of the pin level after initialization */
#define BOARD_INITPINS_INPUT_KEY5_PIN_LEVEL 0U
/* GPIO, 4 signal defines */
/* Definition of the pin direction */
#define BOARD_INITPINS_INPUT_KEY4_PIN_DIRECTION kHAL_GpioDirectionIn
/* Definition of the pin level after initialization */
#define BOARD_INITPINS_INPUT_KEY4_PIN_LEVEL 0U
/* GPIO, 5 signal defines */
/* Definition of the pin direction */
#define BOARD_INITPINS_INPUT_KEY3_PIN_DIRECTION kHAL_GpioDirectionIn
/* Definition of the pin level after initialization */
#define BOARD_INITPINS_INPUT_KEY3_PIN_LEVEL 0U
/* GPIO, 6 signal defines */
/* Definition of the pin direction */
#define BOARD_INITPINS_INPUT_KEY2_PIN_DIRECTION kHAL_GpioDirectionIn
/* Definition of the pin level after initialization */
#define BOARD_INITPINS_INPUT_KEY2_PIN_LEVEL 0U
/* GPIO, 7 signal defines */
/* Definition of the pin direction */
#define BOARD_INITPINS_INPUT_IN5_PIN_DIRECTION kHAL_GpioDirectionIn
/* Definition of the pin level after initialization */
#define BOARD_INITPINS_INPUT_IN5_PIN_LEVEL 0U
/* Definition of peripheral ID */
#define CTIMER1_PERIPHERAL CTIMER1
/* Timer tick frequency in Hz (input frequency of the timer) */
#define CTIMER1_TICK_FREQ 10000000UL
/* Timer tick period in ns (input period of the timer) */
#define CTIMER1_TICK_PERIOD 100UL
/* Definition of PWM period channel. */
#define CTIMER1_PWM_PERIOD_CH kCTIMER_Match_0
/* Definition of channel 0 ID */
#define CTIMER1_MATCH_0_CHANNEL kCTIMER_Match_0
/* Definition of peripheral ID */
#define RTC0_PERIPHERAL RTC0

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern edma_config_t DMA0_config;
/* Destination address extern definition */
extern volatile uint32_t g_adc1DmaBuffer[6];
/* Destination address extern definition */
extern volatile uint32_t g_gpio1SampleBuf[8];
extern edma_handle_t g_adc1DmaHandle;
/* Transactional transfer configurations */
extern edma_transfer_config_t DMA0_CH2_Transfers_config[1];
extern edma_handle_t DMA0_CH1_Handle;
/* Transactional transfer configurations */
extern edma_transfer_config_t DMA0_CH1_Transfers_config[1];
extern const lpuart_config_t LPUART1_config;
extern edma_handle_t LPUART1_RX_Handle;
extern edma_handle_t LPUART1_TX_Handle;
extern lpuart_edma_handle_t LPUART1_LPUART_eDMA_Handle;
extern const ctimer_config_t CTIMER4_config;
extern const ctimer_match_config_t CTIMER4_Match_0_config;
extern pwm_config_t FLEXPWM0_SM0_config;

extern pwm_signal_param_t FLEXPWM0_SM0_pwm_function_config[1];
extern const pwm_fault_input_filter_param_t FLEXPWM0_faultInputFilter_config;
extern const pwm_fault_param_t FLEXPWM0_Fault0_fault_config;
extern const pwm_fault_param_t FLEXPWM0_Fault1_fault_config;
extern const pwm_fault_param_t FLEXPWM0_Fault2_fault_config;
extern const pwm_fault_param_t FLEXPWM0_Fault3_fault_config;
extern const lpuart_config_t LPUART2_config;
extern edma_handle_t LPUART2_RX_Handle;
extern edma_handle_t LPUART2_TX_Handle;
extern lpuart_edma_handle_t LPUART2_LPUART_eDMA_Handle;
extern const lpuart_config_t LPUART3_config;
extern const lpuart_config_t LPUART4_config;
/* LPDAC configuration */
extern const dac_config_t DAC0_config;
extern const crc_config_t CRC0_config;
extern const lpi2c_master_config_t LPI2C1_masterConfig;
extern lpi2c_master_transfer_t LPI2C1_masterTransfer;
extern uint8_t LPI2C1_masterBuffer[LPI2C1_MASTER_BUFFER_SIZE];
extern lpi2c_master_handle_t LPI2C1_masterHandle;
extern const lpspi_master_config_t LPSPI1_config;
extern const ctimer_config_t CTIMER0_config;
extern const ctimer_match_config_t CTIMER0_Match_0_config;
extern const lpadc_config_t ADC1_config;
extern lpadc_conv_command_config_t ADC1_commandsConfig[6];
extern GPIO_HANDLE_DEFINE(BOARD_INITPINS_OUTPUT_KEY_O1_handle);
extern GPIO_HANDLE_DEFINE(BOARD_INITPINS_OUTPUT_KEY_O2_handle);
extern GPIO_HANDLE_DEFINE(BOARD_INITPINS_OUTPUT_KEY_O3_handle);
extern GPIO_HANDLE_DEFINE(BOARD_INITPINS_OUTPUT_KEY_O4_handle);
extern GPIO_HANDLE_DEFINE(BOARD_INITPINS_OUTPUT_KEY_O5_handle);
extern GPIO_HANDLE_DEFINE(BOARD_INITPINS_INPUT_IN1_handle);
extern GPIO_HANDLE_DEFINE(BOARD_INITPINS_INPUT_IN10_handle);
extern GPIO_HANDLE_DEFINE(BOARD_INITPINS_INPUT_KEY6_handle);
extern GPIO_HANDLE_DEFINE(BOARD_INITPINS_INPUT_KEY5_handle);
extern GPIO_HANDLE_DEFINE(BOARD_INITPINS_INPUT_KEY4_handle);
extern GPIO_HANDLE_DEFINE(BOARD_INITPINS_INPUT_KEY3_handle);
extern GPIO_HANDLE_DEFINE(BOARD_INITPINS_INPUT_KEY2_handle);
extern GPIO_HANDLE_DEFINE(BOARD_INITPINS_INPUT_IN5_handle);
extern const ctimer_config_t CTIMER1_config;
extern const ctimer_match_config_t CTIMER1_Match_0_config;
/* RTC configuration */
extern const rtc_config_t RTC0_config;
/* Date and time structure */
extern rtc_datetime_t RTC0_dateTimeStruct;

/***********************************************************************************************************************
 * Global functions
 **********************************************************************************************************************/
/* Get GPIO pin configuration */
hal_gpio_pin_config_t createAdapterGpioPinConfig(GPIO_Type *port, uint8_t pin, hal_gpio_direction_t direction, uint8_t level);

/***********************************************************************************************************************
 * Callback functions
 **********************************************************************************************************************/
/* eDMA callback function for the 2 channel.*/
extern void ADC1_DMA_Callback(edma_handle_t*, void*, bool, uint32_t);
/* eDMA callback function for the 5 channel.*/
extern void GPIO1_SampleDmaCallback(edma_handle_t*, void*, bool, uint32_t);

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
